import Link from 'next/link';
import {isHeritageTheme} from '@/lib/theme-registry';
import ThemeCard from '@/components/ThemeCard';
import {publicSite} from '@/lib/cms-server';
import { categories } from '@/lib/templates';
export const dynamic='force-dynamic';
export async function generateMetadata(){const s=await publicSite();return{title:'Koleksi Tema',robots:{index:s.source==='database'&&s.content.allowIndex,follow:s.source==='database'&&s.content.allowIndex}};}
export default async function Catalog({searchParams}:{searchParams:Promise<{category?:string;q?:string;collection?:string}>}) {
 const site=await publicSite();const templates=site.catalog;const params=await searchParams;const category=typeof params.category==='string'&&categories[params.category]?params.category:'all';const q=typeof params.q==='string'?params.q.trim().slice(0,100):'';
 const heritage=params.collection==='nusantara';
 const visible=templates.filter(t=>t.active&&(!heritage||isHeritageTheme(t.slug))&&(category==='all'||t.category===category)&&(!q||(t.name+' '+t.description).toLowerCase().includes(q.toLowerCase())));
 return <main className="container page-space"><div className="page-heading"><span className="eyebrow">PILIHAN UNTUK MOMEN ANDA</span><h1>Temukan <em>tema favorit.</em></h1><p>Temukan desain yang dekat dengan cerita, keyakinan, dan akar budaya Anda. Coba seluruh demo tanpa login.</p></div><section className="heritage-collection"><div><h2>Islami & pesona Nusantara</h2><p>Lima desain baru: Islami Sakinah, Adat Sunda, Adat Minang, Adat Jawa, dan Adat Bali. Ornamen khas, musik opsional, amplop digital, dan lokasi per acara.</p></div><Link className="button ghost small" href={heritage?'/tema':'/tema?category=pernikahan&collection=nusantara'}>{heritage?'Lihat semua tema':'Jelajahi koleksi baru ↗'}</Link></section><div className="catalog-tools"><nav className="filter-tabs" aria-label="Kategori tema">{Object.entries(categories).map(([key,name])=><Link key={key} className={category===key?'active':''} href={'/tema?category='+key+(q?'&q='+encodeURIComponent(q):'')} aria-current={category===key?'page':undefined}>{name}</Link>)}</nav><form action="/tema" role="search"><input type="hidden" name="category" value={category}/>{heritage&&<input type="hidden" name="collection" value="nusantara"/>}<input aria-label="Cari tema" name="q" defaultValue={q} maxLength={100} placeholder="Cari nama atau gaya…"/><button className="button ghost small">Cari</button></form></div>{site.source==='unavailable'&&<p className="notice error">Katalog database belum dapat dimuat. Harga tidak diganti dengan angka lama. Coba muat ulang.</p>}{site.source==='demo'&&<p className="notice">Mode demo lokal. Harga referensi; bukan katalog layanan yang sudah aktif.</p>}<p className="result-count">{visible.length} tema ditemukan{q?` untuk “${q}”`:''}</p><div className="theme-grid">{visible.map(t=><ThemeCard key={t.slug} template={t} priceLabel={site.source==='demo'?'Harga referensi tema':'Harga katalog saat ini'}/>)}</div>{!visible.length&&site.source!=='unavailable'&&<div className="empty-state"><h2>Tema belum ditemukan</h2><p>Coba kata kunci lain atau buka semua kategori.</p><Link className="button" href="/tema">Reset pencarian</Link></div>}</main>;
}
