import test from 'node:test';import assert from 'node:assert/strict';
import {CommerceController,COMMERCE_INITIAL} from '../lib/commerce-controller.ts';
import {type MutationOutcome,type PendingCommerce,sendCommerce} from '../lib/commerce-transport.ts';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';
const body=()=>({sale_id:B,revision:2,action:'approve',request_id:A,note:'Catatan awal'});
const confirmed:MutationOutcome={state:'confirmed',message:'Dikonfirmasi',result:{id:B,status:'paid',revision:3}};
const uncertain:MutationOutcome={state:'uncertain',message:'Belum pasti'};
function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};}
function setup(send:(p:PendingCommerce)=>Promise<MutationOutcome>=async()=>confirmed,onConfirmed?:(r:Record<string,unknown>)=>void|Promise<void>,owner=A){
 const values=new Map<string,string>(),sent:PendingCommerce[]=[];let blockRead=false,blockWrite=false,blockDelete=false;
 const storage={getItem:(k:string)=>{if(blockRead)throw new Error('READ');return values.get(k)??null;},setItem:(k:string,v:string)=>{if(blockWrite)throw new Error('WRITE');values.set(k,v);},removeItem:(k:string)=>{if(blockDelete)throw new Error('DELETE');values.delete(k);}};
 const controller=new CommerceController({owner,key:'sale:'+B,endpoint:'/api/commerce/action',storage,send:async p=>{sent.push(p);return send(p);},onConfirmed});
 return {controller,storage,values,sent,blocks:{read:(v:boolean)=>{blockRead=v;},write:(v:boolean)=>{blockWrite=v;},delete:(v:boolean)=>{blockDelete=v;}}};
}
test('controller construction and server snapshot perform no browser IO',()=>{const x=setup();x.blocks.read(true);assert.equal(x.controller.getSnapshot(),COMMERCE_INITIAL);assert.equal(x.controller.getServerSnapshot(),COMMERCE_INITIAL);assert.equal(x.values.size,0);});
test('no operation before committed start',async()=>{const x=setup();await x.controller.submit(body());assert.equal(x.sent.length,0);});
test('journal exists before send and confirmed operation is removed',async()=>{const x=setup(async p=>{assert.deepEqual(JSON.parse(x.values.get(x.controller.storageKey)!),p);return confirmed;});x.controller.start();await x.controller.submit(body());assert.equal(x.values.size,0);assert.equal(x.controller.getSnapshot().success,true);assert.equal(x.controller.getSnapshot().busy,false);});
test('double click sends only one operation',async()=>{const wait=deferred<MutationOutcome>(),x=setup(()=>wait.promise);x.controller.start();const a=x.controller.submit(body());await x.controller.submit(body());await x.controller.retry();assert.equal(x.sent.length,1);wait.resolve(confirmed);await a;});
test('caller mutation does not change pending retry payload',async()=>{const x=setup(async()=>uncertain);x.controller.start();const input=body();await x.controller.submit(input);input.note='Changed outside controller';await x.controller.retry();assert.equal(x.sent.length,2);assert.equal(x.sent[1].body.note,'Catatan awal');assert.equal(x.sent[0],x.sent[1]);assert.throws(()=>{x.sent[0].body.note='mutated';});});
test('transport exception preserves journal and always releases busy state',async()=>{const x=setup(async()=>{throw new Error('network');});x.controller.start();await x.controller.submit(body());assert.equal(x.controller.getSnapshot().busy,false);assert.equal(x.controller.getSnapshot().pending,true);assert.equal(x.values.size,1);});
test('refresh/navigation callback failure does not relabel a confirmed payment as failed',async()=>{const x=setup(async()=>confirmed,()=>{throw new Error('render');});x.controller.start();await x.controller.submit(body());assert.equal(x.controller.getSnapshot().success,true);assert.equal(x.controller.getSnapshot().busy,false);assert.equal(x.controller.getSnapshot().pending,false);assert.match(x.controller.getSnapshot().message,/Server mengonfirmasi/);assert.equal(x.values.size,0);});
test('async refresh rejection also releases busy without new payment retry',async()=>{const x=setup(async()=>confirmed,async()=>{throw new Error('refresh');});x.controller.start();await x.controller.submit(body());assert.equal(x.controller.getSnapshot().busy,false);assert.equal(x.controller.getSnapshot().success,true);assert.equal(x.sent.length,1);});
test('unmount suppresses late confirmation, notification, callback and journal deletion',async()=>{const wait=deferred<MutationOutcome>();let callbacks=0,notifications=0;const x=setup(()=>wait.promise,()=>{callbacks++;});x.controller.subscribe(()=>{notifications++;});x.controller.start();const pending=x.controller.submit(body());x.controller.stop();const count=notifications;wait.resolve(confirmed);await pending;assert.equal(callbacks,0);assert.equal(notifications,count);assert.equal(x.values.size,1);});
test('stop/start replay cannot let an older reply clear the new generation',async()=>{const first=deferred<MutationOutcome>(),second=deferred<MutationOutcome>();let calls=0,callbacks=0;const x=setup(()=>++calls===1?first.promise:second.promise,()=>{callbacks++;});x.controller.start();const old=x.controller.submit(body());x.controller.stop();x.controller.start();const replay=x.controller.retry();first.resolve(confirmed);await old;assert.equal(x.controller.getSnapshot().busy,true);assert.equal(x.values.size,1);assert.equal(callbacks,0);second.resolve(confirmed);await replay;assert.equal(callbacks,1);assert.equal(x.values.size,0);});
test('account switch does not replay or remove another account journal',async()=>{const x=setup(async()=>uncertain);x.controller.start();await x.controller.submit(body());x.controller.stop();const next=new CommerceController({owner:C,key:'sale:'+B,endpoint:'/api/commerce/action',storage:x.storage,send:async()=>confirmed});next.start();assert.equal(next.getSnapshot().pending,false);await next.retry();assert.equal(x.values.size,1);assert.notEqual(next.storageKey,x.controller.storageKey);});
test('new controller restores the exact legacy v1 journal without auto sending',async()=>{const x=setup(async()=>uncertain);x.controller.start();await x.controller.submit(body());const wire=x.values.get(x.controller.storageKey);x.controller.stop();let actual:PendingCommerce|null=null;const next=new CommerceController({owner:A,key:'sale:'+B,endpoint:'/api/commerce/action',storage:x.storage,send:async p=>{actual=p;return confirmed;}});next.start();assert.equal(actual,null);assert.equal(next.getSnapshot().pending,true);await next.retry();assert.deepEqual(actual,JSON.parse(wire!));});
test('invalid or other-account journal blocks rather than discards data',()=>{for(const raw of ['not JSON',JSON.stringify({version:1,owner:C,key:'sale:'+B,endpoint:'/api/commerce/action',body:body()})]){const x=setup();x.values.set(x.controller.storageKey,raw);x.controller.start();assert.equal(x.controller.getSnapshot().blocked,true);assert.equal(x.values.get(x.controller.storageKey),raw);}});
test('storage read/write errors do not send',async()=>{const x=setup();x.blocks.read(true);x.controller.start();await x.controller.submit(body());assert.equal(x.sent.length,0);const y=setup();y.controller.start();y.blocks.write(true);await y.controller.submit(body());assert.equal(y.sent.length,0);});
test('delete failure keeps pending and blocks another transaction even after confirmed ACK',async()=>{const x=setup();x.controller.start();x.blocks.delete(true);await x.controller.submit(body());assert.equal(x.controller.getSnapshot().success,true);assert.equal(x.controller.getSnapshot().blocked,true);assert.equal(x.controller.getSnapshot().pending,true);await x.controller.submit(body());await x.controller.retry();assert.equal(x.sent.length,1);});
test('journal replaced during request is never removed by old ACK',async()=>{const wait=deferred<MutationOutcome>(),x=setup(()=>wait.promise);x.controller.start();const call=x.controller.submit(body());x.values.set(x.controller.storageKey,'new journal');wait.resolve(confirmed);await call;assert.equal(x.values.get(x.controller.storageKey),'new journal');assert.equal(x.controller.getSnapshot().blocked,true);});
test('journal externally changed before retry blocks network',async()=>{const x=setup(async()=>uncertain);x.controller.start();await x.controller.submit(body());x.values.delete(x.controller.storageKey);await x.controller.retry();assert.equal(x.sent.length,1);assert.equal(x.controller.getSnapshot().blocked,true);});
test('existing journal after start cannot be overwritten by a new operation',async()=>{const x=setup();x.controller.start();x.values.set(x.controller.storageKey,'another pending');await x.controller.submit(body());assert.equal(x.sent.length,0);assert.equal(x.values.get(x.controller.storageKey),'another pending');});
test('explicit rejection releases original journal',async()=>{const x=setup(async()=>({state:'rejected',message:'Version conflict'}));x.controller.start();await x.controller.submit(body());assert.equal(x.controller.getSnapshot().pending,false);assert.equal(x.controller.getSnapshot().busy,false);assert.equal(x.controller.getSnapshot().success,false);});
test('unknown or wrong confirmation does not clear request',async()=>{const x=setup(async()=>({...confirmed,result:{id:C,status:'paid',revision:3}}));x.controller.start();await x.controller.submit(body());assert.equal(x.controller.getSnapshot().pending,true);assert.equal(x.controller.getSnapshot().success,false);});
test('subscriber errors cannot corrupt mutation bookkeeping',async()=>{const x=setup();x.controller.subscribe(()=>{throw new Error('observer');});x.controller.start();await x.controller.submit(body());assert.equal(x.controller.getSnapshot().busy,false);assert.equal(x.controller.getSnapshot().success,true);});
test('actual commerce transport retry is wired to retained controller snapshot',async()=>{let call=0;const x=setup(p=>sendCommerce(p,(async()=>{if(++call===1)return new Response('{"error":"timeout"}',{status:408,headers:{'Content-Type':'application/json'}});return new Response(JSON.stringify({ok:true,result:confirmed.result}),{headers:{'Content-Type':'application/json'}});}) as typeof fetch,100));x.controller.start();await x.controller.submit(body());assert.equal(x.controller.getSnapshot().pending,true);await x.controller.retry();assert.equal(x.controller.getSnapshot().success,true);assert.deepEqual(x.sent[0],x.sent[1]);});
