/** Static source contracts, not executed PostgreSQL policies or browser sessions. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=(p:string)=>readFileSync(new URL('../'+p,import.meta.url),'utf8'),sql=read('supabase/migrations/005_guestbook_rsvp.sql');
const fn=(name:string)=>sql.split('create or replace function public.'+name+'(')[1]?.split('create or replace function ')[0]||'';
test('005 is additive transaction with explicit schema prerequisites and version5',()=>{assert.match(sql,/\nbegin;/);assert.match(sql,/commit;\s*$/);assert.ok(sql.includes('not in (4,5)'));assert.ok(sql.includes('as $$ select 5; $$'));assert.ok(!/^\s*(drop table|truncate)\b/im.test(sql));});
test('all guest tables enable RLS and no anonymous/direct read grants exist',()=>{for(const table of ['ki_guest_platform','ki_guest_settings','ki_guests','ki_rsvps','ki_guest_mutations'])assert.ok(sql.includes('alter table public.'+table+' enable row level security;'));assert.ok(sql.includes('revoke all on public.ki_guest_platform,public.ki_guest_settings,public.ki_guests,public.ki_rsvps,public.ki_guest_mutations from public,anon,authenticated'));assert.ok(!/grant (select|insert|update|delete|all) /i.test(sql));});
test('all SQL functions fix search path and revoke default execution',()=>{for(const [,name,body]of sql.matchAll(/create or replace function public\.(\w+)([\s\S]*?)(?=create or replace function|notify pgrst|$)/g)){assert.ok(body.includes("set search_path=''"),name);assert.ok(body.includes('revoke all on function public.'+name),name);}});
test('owner workspace/export/reveal/mutations never give admin cross-owner override',()=>{for(const name of ['ki_guest_workspace','ki_guest_export','ki_guest_link','ki_guest_manage']){const body=fn(name);assert.ok(body.includes('owner_id=')&&body.includes('ki_has_confirmed_email()'),name);assert.ok(!body.includes('ki_is_admin()'),name);assert.ok(!body.includes('to anon,authenticated'),name);}});
test('global settings require allowlisted admin and confirmed email',()=>{for(const n of ['ki_guest_platform_read','ki_guest_platform_update']){assert.ok(fn(n).includes('not public.ki_is_admin() or not public.ki_has_confirmed_email()'));assert.ok(!fn(n).includes('to anon'));}});
test('public RPC permissions are granted only for three scoped projections/writes',()=>{const names=[...sql.matchAll(/grant execute on function public\.(\w+)[^;]+to anon,authenticated/g)].map(m=>m[1]);assert.deepEqual(names.sort(),['ki_guest_context','ki_public_wishes','ki_schema_version','ki_submit_rsvp'].sort());});
test('list and CSV SQL projections contain no bearer tokens or raw retry payloads',()=>{for(const n of ['ki_guest_workspace','ki_guest_export']){assert.ok(!/g\.token|last_payload|last_result/.test(fn(n)),n);}assert.ok(fn('ki_guest_link').includes("'token',g.token"));});
test('public wishes require active paid unexpired publication plus consent and moderation',()=>{const live=fn('ki_guest_live_sale');for(const t of ["s.status='paid'",'s.expires_at>now()','p.active','publishing_enabled','ki_guest_platform'])assert.ok(live.includes(t),t);const wishes=fn('ki_public_wishes');for(const t of ['show_wishes','g.active','r.consent',"r.moderation='approved'",'limit 21','limit 20'])assert.ok(wishes.includes(t),t);assert.ok(!wishes.includes('g.name')&&!wishes.includes('g.token')&&!wishes.includes("'people'"));});
test('respond validates token binding, capacity and serializes writes behind live gates',()=>{const b=fn('ki_submit_rsvp');for(const t of ['for share','for update','sale_id=sid and token=p_token and active','p_people>g.max_people','expires_at>clock_timestamp()','current_revision<>p_revision'])assert.ok(b.includes(t),t);assert.ok(b.indexOf('r.last_request=p_request')<b.indexOf('if not accepting_now'));assert.ok(b.indexOf('r.last_request=p_request')<b.indexOf('Rate limited'));});
test('edits reset moderation and consent withdrawal bypasses closure/rate without changing attendance',()=>{const b=fn('ki_submit_rsvp');assert.ok(b.includes("moderation=case when p_consent then 'pending' else 'hidden' end"));assert.ok(b.includes('r.attendance=p_attendance and r.people=p_people and r.message=trim(p_message)'));assert.ok(b.includes('not accepting_now and not withdrawal'));assert.ok(b.includes('if not withdrawal and current_revision>0'));assert.ok(fn('ki_guest_manage').includes("not r.consent or trim(r.message)=''"));});
test('owner retry log, guest limits, capacity lowering and key rotation are enforced in SQL',()=>{const b=fn('ki_guest_manage');for(const t of ['prior.request_payload<>payload','return prior.result','offset 512','count_new not between 1 and 25','+count_new>500','Capacity below response',"token=replace(gen_random_uuid()::text||gen_random_uuid()::text"])assert.ok(b.includes(t),t);assert.ok(fn('ki_submit_rsvp').includes("interval '30 seconds'"));assert.ok(fn('ki_submit_rsvp').includes('r.rate_count>=20'));});
test('all owner API mutations/readers authenticate; public routes check origin and feature gate',()=>{for(const p of ['manage','workspace','link','export'])assert.ok(read('app/api/guestbook/'+p+'/route.ts').includes('await apiUser(request)'));for(const p of ['guest','respond','wishes']){const s=read('app/api/public/[slug]/'+p+'/route.ts');assert.ok(s.includes('checkOrigin(request)'));assert.ok(s.includes('requireRsvpApp()'));assert.ok(!s.includes('privateStorageDb'));}});
test('committed but unparseable mutation ack is 503 and retryable',()=>{for(const p of ['app/api/guestbook/manage/route.ts','app/api/public/[slug]/respond/route.ts'])assert.ok(read(p).includes("throw new HttpError(503,'Balasan belum dapat dipastikan"));});
test('public form is not demo simulation and internal scroll preserves bearer fragment',()=>{const v=read('components/InvitationView.tsx');assert.ok(v.includes("mode==='public'&&rsvpSlug&&<PublicRsvp"));assert.ok(v.includes('e.preventDefault();document.getElementById(eventId)?.scrollIntoView'));assert.ok(read('components/guests/PublicRsvp.tsx').includes('decodeRsvpPending'));});
test('retained request writes journal before send and retains unknown outcomes',()=>{const s=read('components/guests/useRetainedRequest.ts');assert.ok(s.indexOf('sessionStorage.setItem(storageKey,raw)')<s.indexOf('await transmit(p)'));assert.ok(s.includes('if(!error.uncertain)clear()'));assert.ok(s.includes('current!==epoch.current'));assert.ok(s.includes('pendingRef.current?transmit(pendingRef.current)'));});
test('stage5 is default closed and current editor/checkouts require current version6',()=>{assert.ok(read('.env.example').includes('ENABLE_RSVP=false'));assert.ok(read('scripts/env-tools.mjs').includes('ENABLE_RSVP'));for(const p of ['app/dashboard/baru/page.tsx','app/dashboard/undangan/[id]/page.tsx','app/dashboard/undangan/[id]/pesan/page.tsx'])assert.ok(read(p).includes('version!==7'));assert.ok(read('lib/readiness.ts').includes('result.status === 404'));});

test('SQL protects list decoding against controls and astral overlength via direct RPC',()=>{const helper=fn('ki_guest_valid_text');assert.ok(helper.includes('ascii(ch)>65535 then 2'));assert.ok(helper.includes("'[[:cntrl:]]'"));assert.ok(fn('ki_submit_rsvp').includes('not public.ki_guest_valid_text(p_message,0,500)'));assert.ok(fn('ki_guest_manage').includes("not public.ki_guest_valid_text(item->>'name',1,100)"));});
