/** Source contracts only: not executed PostgreSQL, Supabase policies, or browser E2E. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const read=(p:string)=>readFileSync(new URL('../'+p,import.meta.url),'utf8'),sql=read('supabase/migrations/006_cms_operations.sql');
const fn=(name:string)=>sql.split('create or replace function public.'+name+'(')[1]?.split('create or replace function ')[0]||'';
test('006 is additive, version-gated, and preserves payment/guest feature gates',()=>{assert.match(sql,/\nbegin;/);assert.match(sql,/commit;\s*$/);assert.ok(sql.includes('not in (5,6)'));assert.ok(sql.includes('as $$ select 6; $$'));assert.ok(!/^\s*(drop table|truncate)/im.test(sql));assert.ok(!/update public\.(ki_sales|ki_publications|ki_guest_platform|ki_commerce_settings)\b/i.test(sql));});
test('CMS table access is revoked and RLS enabled; read/write only through scoped RPC',()=>{for(const t of ['ki_cms','ki_cms_history','ki_cms_events'])assert.ok(sql.includes('alter table public.'+t+' enable row level security;'));assert.ok(sql.includes('revoke all on public.ki_cms,public.ki_cms_history,public.ki_cms_events from public,anon,authenticated;'));assert.ok(!/grant (select|update|insert|all) on public\.ki_cms/i.test(sql));});
test('CMS functions use fixed search_path and explicit execution revocation',()=>{for(const[,name,body]of sql.matchAll(/create or replace function public\.(\w+)([\s\S]*?)(?=create or replace function|notify pgrst|$)/g)){assert.ok(body.includes("set search_path=''"),name);assert.ok(body.includes('revoke all on function public.'+name),name);}});
test('CMS admin read, mutator and operations check admin plus confirmed email',()=>{for(const n of ['ki_cms_read','ki_cms_mutate','ki_admin_overview','ki_admin_customers']){assert.ok(fn(n).includes('not public.ki_is_admin()'),n);assert.ok(fn(n).includes('not public.ki_has_confirmed_email()'),n);assert.ok(!fn(n).includes('to anon,authenticated'),n);}});
test('CMS public RPC exposes only published content and live active catalog',()=>{const p=fn('ki_cms_public');assert.ok(p.includes("c.published->'content'"));assert.ok(p.includes("item->'active'='true'::jsonb"));assert.ok(!/c\.draft|ki_cms_events|ki_cms_history/.test(p));});
test('CMS mutation serializes against other edits and retries before version/rate checks',()=>{const b=fn('ki_cms_mutate');assert.ok(b.includes('where id=1 for update'));assert.ok(b.indexOf('return prior.result')<b.indexOf('c.revision<>p_revision'));assert.ok(b.indexOf('return prior.result')<b.indexOf('CMS rate limit'));assert.ok(b.includes('prior.payload<>payload'));assert.ok(b.includes('actor_id=actor and request_id=p_request'));});
test('CMS publish source is saved draft and old sales snapshots are untouched',()=>{const b=fn('ki_cms_mutate');assert.ok(b.includes("p_action='publish' and p_document is not null"));assert.ok(b.includes('set published=draft'));assert.ok(b.includes('update public.ki_templates'));assert.ok(!b.includes('update public.ki_sales'));assert.ok(b.includes('insert into public.ki_cms_history'));});
test('CMS detects out-of-band price edits before save AND publish',()=>{const b=fn('ki_cms_mutate');assert.ok(b.indexOf('md5(live_catalog::text)<>p_catalog_hash')<b.indexOf("if p_action='save' then"));assert.ok(b.includes('order by slug for update'));});
test('retired templates remain editable only on unchanged owned draft',()=>{const b=fn('ki_save_draft');assert.ok(b.includes('own.id=p_id and own.owner_id=actor and own.theme_slug=p_theme'));assert.ok(b.includes('ki_deleted_drafts'));assert.ok(b.includes('p_expected_revision'));});
test('CMS bootstrap preserves existing database prices; public prices never fall back on outage',()=>{assert.ok(sql.includes("'catalog',public.ki_cms_catalog()"));assert.ok(read('lib/cms-server.ts').includes("catalog:[],revision:0,source:'unavailable'"));for(const file of ['app/page.tsx','app/harga/page.tsx','app/tema/page.tsx','app/order/[slug]/page.tsx'])assert.ok(read(file).includes('await publicSite()'));});
test('CMS API authenticates, verifies admin and treats malformed post-commit ACK as uncertain',()=>{const s=read('app/api/admin/cms/route.ts');for(const t of ['await apiUser(request)',"db.rpc('ki_is_admin')",'user.email_confirmed_at','parseCmsCommand(await readBody(request))','parseCmsAck(data,x)','throw new HttpError(503'])assert.ok(s.includes(t),t);});
test('CMS UI uses retained request and explicit saved-draft publication consent',()=>{const s=read('components/cms/CmsEditor.tsx');for(const t of ['useRetainedRequest','decodeCmsPending','encodeCmsPending','if(dirty||!checked||locked)return','Preview draft server','Muat Published','Simpan draft'])assert.ok(s.includes(t));assert.ok(!/dangerouslySetInnerHTML|innerHTML\s*=/.test(s));});
test('CMS page output renders text not HTML, no new secrets or public admin flag',()=>{for(const p of ['components/cms/MarketingHome.tsx','components/cms/CmsEditor.tsx','components/SiteHeader.tsx','components/SiteFooter.tsx'])assert.ok(!read(p).includes('dangerouslySetInnerHTML'));assert.ok(!read('.env.example').includes('NEXT_PUBLIC_ADMIN'));});
test('operational directory never enumerates Auth users or private customer drafts/guests',()=>{const b=fn('ki_admin_customers');assert.ok(b.includes('from public.ki_sales group by owner_id'));assert.ok(b.includes('limit 20'));assert.ok(!/from auth\.users|from public\.(ki_invitations|ki_guests|ki_rsvps)/.test(b));});
test('all current editor/checkouts and readiness require schema7',()=>{for(const p of ['app/dashboard/baru/page.tsx','app/dashboard/undangan/[id]/page.tsx','app/dashboard/undangan/[id]/pesan/page.tsx'])assert.ok(read(p).includes('version!==7'));assert.ok(read('lib/readiness.ts').includes('result.body === BASE_SCHEMA_VERSION'));});

test('marketing robots policy follows CMS and stays closed on failure/demo',()=>{const s=read('app/robots.ts');assert.ok(s.includes("s.source!=='database'||!s.content.allowIndex"));assert.ok(s.includes("disallow:'/'"));for(const p of ["'/$'","'/tema$'","'/harga$'"])assert.ok(s.includes(p));assert.ok(s.includes("dynamic='force-dynamic'"));});
test('CMS offers a guarded server refresh after a conflict, with no forced overwrite',()=>{const s=read('components/cms/CmsEditor.tsx');assert.ok(s.includes('Perbarui data server'));assert.ok(s.includes("function refresh(){if(locked)return"));assert.ok(!s.includes('forceOverwrite'));assert.ok(read('scripts/test-supabase.mjs').includes('version.data === 7'));});
