import Link from 'next/link';
export const metadata={title:'Panduan Membuat & Membagikan Undangan'};
const steps=[
 {id:'isi-undangan',title:'Pilih tema & isi undangan',text:'Coba demo tema, lalu masuk atau daftar untuk membuat draft. Lengkapi nama pasangan, tanggal, waktu, zona waktu, dan lokasi acara. Cerita serta foto dapat ditambahkan sesuai kebutuhan.',note:'Pastikan status simpan berhasil, lalu periksa preview sebelum memesan.',href:'/tema',action:'Lihat koleksi tema'},
 {id:'pembayaran',title:'Buat pesanan & transfer',text:'Pilih Pesan & terbitkan dari dashboard atau editor. Periksa tema, harga, rekening, dan masa aktif pada pesanan. Transfer sesuai rincian tersebut, lalu isi konfirmasi transfer dengan nama pengirim, referensi, dan waktu transfer.',note:'Jangan transfer sebelum nomor pesanan dan rekening muncul. Gunakan tombol salin rekening dan nominal untuk membantu menghindari salah ketik.',href:'/dashboard/pesanan',action:'Lihat pesanan saya'},
 {id:'verifikasi',title:'Tunggu verifikasi pembayaran',text:'Setelah konfirmasi dikirim, admin memeriksa pembayaran. Buka detail pesanan dan gunakan Periksa ulang untuk melihat status terbaru. Jika konfirmasi ditolak, baca catatan admin sebelum memperbaikinya.',note:'Konfirmasi terkirim belum berarti pembayaran disetujui. Jangan transfer ulang hanya karena status belum berubah.'},
 {id:'terbitkan',title:'Periksa & terbitkan',text:'Setelah pembayaran disetujui, buka bagian Siap dibagikan? pada detail pesanan. Lengkapi checklist, periksa preview, pilih alamat undangan, setujui penayangan konten, lalu tekan Terbitkan undangan.',note:'Alamat tidak dapat diganti setelah publikasi pertama. Siapa pun yang mempunyai tautan dapat membaca undangan.'},
 {id:'bagikan',title:'Bagikan kepada tamu',text:'Pada bagian Bagikan kabar bahagia, isi nama tamu bila diperlukan. Periksa pratinjau pesan, lalu pilih Salin pesan & tautan, Salin tautan, atau Buka WhatsApp. Anda memeriksa dan mengirim sendiri pesan di WhatsApp.',note:'Pesan memakai versi yang sudah terbit. Nama tamu pada tautan umum hanya mengubah sapaan; untuk RSVP gunakan tautan khusus tamu.'},
];
const questions=[
 ['Bagaimana menambahkan musik dan amplop digital?','Buka Musik & hadiah di editor. Pilih Serenade untuk musik instrumental, lalu tambahkan hingga tiga rekening bank atau dompet digital jika diperlukan. Isi nomor hanya dengan angka, termasuk awalan nol, dan periksa nama pemilik. Simpan dan terbitkan versi terbaru agar tamu melihat perubahan. Musik dimulai setelah tamu membuka undangan, bisa dijeda, dan berhenti saat beralih tab. Rekening hadiah tampil publik sesuai persetujuan penerbitan.'],
 ['Sudah transfer, tetapi belum bisa terbit?','Pastikan konfirmasi transfer sudah dikirim dari detail pesanan. Jika sedang diperiksa, tunggu verifikasi admin dan gunakan Periksa ulang. Jika ditolak, baca alasannya. Setelah disetujui, lengkapi checklist publikasi dan persetujuan konten. Jangan membayar ulang tanpa memeriksa pesanan atau menghubungi pengelola.'],
 ['Isi berubah, tetapi tamu masih melihat versi lama?','Simpan perubahan di editor, periksa preview, lalu buka detail pesanan dan tekan Terbitkan versi terbaru. Mengedit draft saja tidak mengubah halaman tamu. Tautan undangan tetap sama.'],
 ['Apa yang dilakukan saat koneksi terputus?','Jangan tutup tab editor sebelum memastikan status simpan. Saat koneksi kembali, gunakan Coba simpan kembali jika tersedia. Unduh salinan draft sebelum berpindah perangkat; salinan tidak memuat berkas foto. Jika ada konflik dua tab, simpan salinan perubahan sebelum memuat ulang data. Untuk pesanan atau publikasi yang hasilnya belum pasti, gunakan Coba ulang permintaan yang sama dan periksa status terbaru. Jangan membuat pesanan atau transfer baru hanya karena terjadi gangguan.'],
 ['Bagaimana memasang lokasi Google Maps?','Buka editor → Acara & lokasi. Isi nama tempat dan alamat, lalu cari lokasi di Google Maps. Pilih Bagikan → Salin link dan tempel ke Link Google Maps. Gunakan Periksa titik lokasi untuk memastikan pin sudah tepat. Akad dan resepsi boleh memiliki link berbeda. Simpan draft dan terbitkan versi terbaru; tamu akan melihat tombol Buka Google Maps pada masing-masing acara.'],
 ['Bagaimana mengatur acara dan foto?','Undangan mendukung hingga tiga acara dan enam foto. Acara pertama menjadi tanggal utama di sampul. Periksa zona waktu dan lokasi setiap acara. Pilih foto JPEG, PNG, atau WebP maksimal 5 MB per berkas; foto pertama menjadi sampul. Setelah unggah atau mengubah urutan, pastikan draft berhasil disimpan.'],
 ['Kapan masa aktif dimulai?','Masa aktif dimulai saat pembayaran disetujui admin. Tanggal berakhir tercantum pada detail pesanan. Mengedit, menarik dari publik, atau menerbitkan ulang tidak memperpanjang masa aktif. Hubungi pengelola bila masa aktif berakhir.'],
 ['Bisakah undangan ditarik dari publik?','Gunakan Tarik dari publik pada detail pesanan. Masa aktif tetap berjalan. Salinan yang sudah disimpan atau diteruskan tamu tidak dapat ditarik kembali. Pembatalan atau pencabutan akses tidak otomatis mengembalikan dana; hubungi pengelola untuk pembahasan pembayaran.'],
];
export default function Guide(){return <main className="container page-space customer-guide">
 <header className="page-heading"><span className="eyebrow">PANDUAN PELANGGAN</span><h1>Dari cerita Anda,<br/><em>sampai ke tangan tamu.</em></h1><p>Ikuti lima langkah untuk menyiapkan, menerbitkan, dan membagikan undangan.</p></header>
 <nav className="guide-nav" aria-label="Bagian panduan">{steps.map((s,i)=><a key={s.id} href={'#'+s.id}>{i+1}. {['Isi undangan','Bayar','Verifikasi','Terbitkan','Bagikan'][i]}</a>)}<a href="#bantuan">Bantuan</a><a href="#tamu-rsvp">Tamu & RSVP</a><a href="#ucapan-umum">Ucapan umum</a></nav>
 <div className="guide-steps">{steps.map((s,i)=><section key={s.id} id={s.id} className="panel guide-step"><span className="guide-number" aria-hidden="true">0{i+1}</span><div><h2>{s.title}</h2><p>{s.text}</p><p className="notice">{s.note}</p>{s.href&&<Link className="text-link" href={s.href}>{s.action} →</Link>}</div></section>)}</div>
 <section id="bantuan" className="panel guide-help"><span className="eyebrow">SAAT MEMBUTUHKAN BANTUAN</span><h2>Pertanyaan yang sering muncul</h2>{questions.map(([title,body])=><details key={title}><summary>{title}</summary><p>{body}</p></details>)}</section>
 <section id="ucapan-umum" className="panel guide-help"><span className="eyebrow">TANPA TAUTAN PERSONAL</span><h2>Ucapan & doa umum</h2><p>Buka Dashboard → Ucapan umum → pilih pesanan. Setelah layanan dibuka pengelola, centang Terima ucapan dan Tampilkan ucapan sesuai kebutuhan, lalu Simpan pengaturan. Undangan harus terbit, pembayaran terverifikasi, dan masa aktif berlaku.</p><p>Bagikan tautan umum dari panel Terbit. Tamu dapat menulis nama dan ucapan tanpa login atau konfirmasi kehadiran. Pesan tidak otomatis tampil: tamu memberi izin dan pemilik menyetujui dari daftar Menunggu moderasi. Pesan tanpa izin tetap privat dan tidak bisa dipaksa tampil.</p><p>Tamu dapat menyimpan kode penghapusan setelah mengirim. Buka halaman penghapusan dan tempel kode secara privat untuk menghapus nama/pesan. Kode hilang dapat ditangani dengan menghubungi pemilik undangan. Menutup penerimaan berbeda dari menyembunyikan daftar yang sudah terbit.</p><Link className="text-link" href="/dashboard/ucapan">Kelola ucapan umum →</Link></section>
 <section id="tamu-rsvp" className="panel guide-help"><span className="eyebrow">FITUR TAMBAHAN</span><h2>Tamu & RSVP</h2><p>RSVP dapat digunakan bila fitur sudah diaktifkan pengelola, pembayaran disetujui, masa aktif berlaku, dan undangan sudah terbit. Jika belum tersedia, Anda tetap dapat membagikan tautan undangan umum.</p>
 <details><summary>Bagaimana membagikan tautan RSVP?</summary><p>Buka Tamu & RSVP dari pesanan, tambahkan tamu, lalu buka penerimaan dan pilih Tautan & WhatsApp. Bagikan tautan personal hanya kepada tamu yang sesuai. Siapa pun yang memperoleh tautan lengkap dapat mengubah jawaban rombongan tersebut. Mengganti kunci tautan membatalkan tautan lama tanpa menghapus jawaban yang sudah tersimpan.</p><Link className="text-link" href="/dashboard/tamu">Buka Tamu & RSVP →</Link></details>
 <details><summary>Bagaimana melihat kehadiran dan ucapan?</summary><p>Satu tautan menyimpan jawaban terbaru satu tamu atau rombongan. Jumlah hadir tidak boleh melebihi kapasitas yang Anda tetapkan. Rekap merupakan rencana kehadiran, bukan bukti check-in.</p><p>Ucapan hanya tampil publik setelah tamu memberi izin dan Anda menyetujuinya. Ucapan yang diedit perlu diperiksa kembali. Daftar tamu dan jawaban kehadiran tetap privat; simpan hasil ekspor CSV dengan hati-hati.</p></details>
 <p className="guide-limits">Pembayaran otomatis, unggah bukti transfer, unggah musik sendiri, QRIS hadiah, pengiriman WhatsApp massal, dan QR check-in belum tersedia.</p></section>
 <section className="panel guide-cta"><h2>Lanjutkan undangan Anda</h2><p>Buka dashboard untuk mengedit draft atau memeriksa pesanan.</p><div className="button-row"><Link className="button" href="/dashboard">Buka dashboard</Link><Link className="button ghost" href="/dashboard/pesanan">Lihat pesanan</Link></div></section>
 </main>;}
