import Link from 'next/link';
import BackendCheck from '@/components/BackendCheck';
export const metadata = {title:'Aktivasi Supabase',robots:{index:false,follow:false}};
export default function Setup(){return <main className="container prose page-space">
 <span className="eyebrow">TAHAP 7 / DATABASE, CMS & OPERASIONAL</span><h1>Hubungkan ruang<br/><em>cerita Anda.</em></h1>
 <p>Demo terbuka tanpa akun. Editor privat menggunakan Supabase dengan skema versi 7. Pemeriksaan ini tidak membuat tabel, mengirim pembayaran, atau menerbitkan undangan.</p><BackendCheck/>
 <section className="panel"><h2>1. Sesuaikan versi database</h2><p>Gunakan proyek khusus Invitation yang sama dengan tahap sebelumnya agar akun dan draft tetap berada di tempatnya. File SQL berada di <code>supabase/migrations</code>.</p>
 <p><strong>Sudah memasang 001–006?</strong> Jalankan hanya <code>007_release_hardening.sql</code>. Proyek baru menjalankan 001 → 002 → 003 → 004 → 005 → 006 → 007 secara berurutan. Jangan menghapus tabel atau menjalankan ulang versi lama setelah versi baru.</p>
 <h2>2. Periksa konfigurasi dan email</h2><p>Pertahankan konfigurasi <code>.env.local</code> dari aplikasi Next.js yang benar. Proyek baru memakai contoh di <code>.env.example</code>. Jangan memasukkan password database, <code>sb_secret_</code>, atau <code>service_role</code> ke variabel publik.</p><p>Provider email, konfirmasi email, Site URL, Redirect URLs, dan template tetap mengikuti <code>docs/TAHAP_2_SUPABASE.md</code>. Baca pembaruan pada <code>docs/TAHAP_7_RILIS.md</code>. Restart atau redeploy setelah perubahan environment.</p>
 <p>Tahap 7: undangan publik membutuhkan <code>SUPABASE_SECRET_KEY</code> dan <code>RATE_LIMIT_HMAC_KEY</code> khusus server, termasuk undangan tanpa foto. Katalog dan editor privat tetap dapat diuji sebelum layanan publik dibuka.</p><h2>3. Uji data, bukan hanya indikator</h2><p>Setelah koneksi merespons skema 7, uji daftar → konfirmasi email → login → simpan draft → buka kembali. Coba dua akun berbeda dan pastikan draft maupun foto tidak terbuka lintas akun. Halaman ini tidak membuktikan email sudah diterima atau RLS sudah diuji dengan penyerang.</p>
 <h2>4. Uji editor bertahap</h2><p>Isi pasangan, pisahkan akad dan resepsi, unggah foto, lalu perhatikan status simpan. Coba ganti tema dan buka preview. Ikuti <code>docs/UJI_EDITOR_TAHAP3.md</code> untuk uji koneksi terputus, pemulihan, dan konflik dua tab.</p>
 <h2>5. Periksa dari akun admin</h2><p><Link href="/admin/sistem">Status sistem</Link> menampilkan metadata RLS, bucket privat dan izin tabel. Tetap gunakan <code>ENABLE_ORDER_REQUESTS=false</code>. Atur rekening melalui <Link href="/admin/transaksi">Pengaturan transaksi</Link> setelah uji. ENABLE_CHECKOUT dan ENABLE_PUBLIC_INVITATIONS tetap false sebelum pengujian tahap 4. Untuk RSVP, aktifkan layanan dari <Link href="/admin/tamu">Admin → Tamu & RSVP</Link> setelah uji. ENABLE_RSVP tetap false sebelum aktivasi sengaja. Indikator berhasil bukan persetujuan peluncuran komersial.</p><h2>6. Uji CMS</h2><p>Buka <Link href="/admin/cms">Admin → CMS website</Link>. Ubah satu teks, simpan draft, periksa preview, lalu publish. Pastikan beranda, katalog, harga, serta checkout baru sesuai. Jangan mengubah harga langsung melalui SQL ketika CMS sedang diedit. Salinan sebelum edit tersedia melalui Unduh salinan.</p></section>
 <div className="button-row"><Link className="button" href="/dashboard">Buka dashboard ↗</Link><Link className="button ghost" href="/panduan">Panduan editor</Link></div>
 </main>;}
