'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {currency, invitationEvents, withEvents, safeGuest} from '@/lib/domain';
import type {DraftContent, Invitation, InvitationEvent, Template} from '@/lib/types';
import {weddingTemplates,getTemplate} from '@/lib/templates';
import {browserDb} from '@/lib/supabase/client';
import {preparePhoto} from '@/lib/photo';
import {completion,createBackup,readBackup,movePhoto} from '@/lib/editor-document';
import {useDraftEditor} from './editor/useDraftEditor';
import {usePrivatePhotos} from './editor/usePrivatePhotos';
import InvitationView from './InvitationView';
import EventMapField from './editor/EventMapField';
import EventLocationReview from './editor/EventLocationReview';
import InvitationExtrasEditor from './editor/InvitationExtrasEditor';
const tabs=[['pasangan','Pasangan'],['acara','Acara & lokasi'],['cerita','Cerita'],['galeri','Galeri'],['extras','Musik & hadiah'],['review','Tema & review']] as const;
type Section=typeof tabs[number][0];
export default function DraftEditor({id,ownerId,initial,initialTheme,themeOptions=weddingTemplates}:{id:string;ownerId:string;initial:Invitation|null;initialTheme:string;themeOptions?:Template[]}) {
  const {controller,state,autosave,setAutosave,dirty}=useDraftEditor(id,ownerId,initial,initialTheme);
  const {content,theme}=state.document;
  const {urls:photos,error:photoError,reload:reloadPhotos}=usePrivatePhotos(content.photoPaths);
  const [section,setSection]=useState<Section>('pasangan'),[pane,setPane]=useState<'form'|'preview'>('form');
  const [guest,setGuest]=useState('Tamu Undangan'),[uploading,setUploading]=useState(false),[uploadNote,setUploadNote]=useState(''),[fileNotice,setFileNotice]=useState('');
  useEffect(()=>{const openSection=()=>{const key=window.location.hash.slice(1);if(tabs.some(([id])=>id===key)){setSection(key as Section);setPane('form');}};openSection();window.addEventListener('hashchange',openSection);return()=>window.removeEventListener('hashchange',openSection);},[]);
  const uploadingRef=useRef(false),importInput=useRef<HTMLInputElement>(null);
  const chosen=themeOptions.find(t=>t.slug===theme)||getTemplate(theme)||weddingTemplates[0], events=invitationEvents(content),checks=completion(content),done=checks.filter(c=>c.done).length;
  const locked=state.phase==='recovery'||state.phase==='auth';
  function updateContent(next:DraftContent) {controller.edit({...controller.getSnapshot().document,content:next});controller.resumeAfterEdit();}
  function update<K extends keyof DraftContent>(key:K,value:DraftContent[K]) {updateContent({...controller.getSnapshot().document.content,[key]:value});}
  function updateEvent(index:number,key:keyof InvitationEvent,value:string){
    const current=controller.getSnapshot().document.content;
    const next=invitationEvents(current).map((event,i)=>i===index?{...event,[key]:value}:event);
    updateContent(withEvents(current,next));
  }
  function addEvent(){const current=controller.getSnapshot().document.content, rows=invitationEvents(current);if(rows.length>=3)return;updateContent(withEvents(current,[...rows,{...rows[0],id:crypto.randomUUID(),label:rows.length===1?'Resepsi':'Acara tambahan'}]));}
  function removeEvent(index:number){if(events.length<=1||!window.confirm('Lepas acara ini dari draft? Perubahan akan mengikuti pengaturan simpan Anda.'))return;const current=controller.getSnapshot().document.content;updateContent(withEvents(current,invitationEvents(current).filter((_,i)=>i!==index)));}
  async function upload(files:File[]){
    if(!files.length||uploadingRef.current||locked||!state.online)return;
    uploadingRef.current=true;setUploading(true);setUploadNote('Menyiapkan foto…');
    let uploaded=0;const failures:string[]=[];
    try{
      const capacity=6-controller.getSnapshot().document.content.photoPaths.length;
      if(files.length>capacity)failures.push(`Hanya ${Math.max(capacity,0)} foto pertama yang diproses agar total tidak melebihi 6.`);
      for(const [index,file] of files.slice(0,Math.max(0,capacity)).entries()){
        if(controller.getSnapshot().phase==='auth') {failures.push('Sesi berakhir. Unggahan berikutnya dihentikan.');break;}
        setUploadNote(`Memproses foto ${index+1} dari ${Math.min(files.length,capacity)}…`);
        try{
          const blob=await preparePhoto(file), path=`${ownerId}/${crypto.randomUUID()}.webp`;
          const {error}=await browserDb().storage.from('ki-media').upload(path,blob,{contentType:'image/webp',upsert:false});
          if(error)throw new Error('unggahan tidak terkonfirmasi; periksa koneksi dan Storage.');
          const current=controller.getSnapshot();
          if(current.phase==='auth') {failures.push('Foto sudah diunggah tetapi belum ditautkan karena sesi berubah. Login sebagai pemilik untuk memeriksa Storage.');break;}
          // Read latest state after await: never discard edits/photos added during upload.
          update('photoPaths',[...current.document.content.photoPaths,path]); uploaded++;
        }catch(error){failures.push(`Foto ${index+1}: ${error instanceof Error?error.message:'gagal diproses.'}`);}
      }
    }finally{uploadingRef.current=false;setUploading(false);setUploadNote(`${uploaded} foto berhasil diunggah secara privat. ${failures.join(' ')}${uploaded?' Referensi foto mengikuti simpan draft.':''}`);}
  }
  function exportBackup(){
    const raw=createBackup(controller.getSnapshot().document,ownerId),url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));
    const a=document.createElement('a');a.href=url;a.download=`kastriva-draft-${id.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  async function importBackup(file:File|undefined){
    if(!file||locked||state.pending||uploading)return;
    try{
      if(file.size>128*1024)throw new Error('Ukuran JSON maksimal 128 KB.');
      const next=readBackup(await file.text(),ownerId);
      if(!window.confirm('Muat isi salinan ini ke formulir? Simpan otomatis akan dijeda agar Anda dapat memeriksa hasilnya. Foto harus masih tersedia pada akun yang sama.'))return;
      setAutosave(false);controller.edit(next);controller.resumeAfterEdit();setFileNotice('Salinan dimuat ke formulir, belum disimpan ke server. Periksa lalu tekan Simpan sekarang.');
    }catch(error){setFileNotice(error instanceof Error?error.message:'Salinan JSON tidak dapat dibaca.');}
  }
  const field=(key:Exclude<keyof DraftContent,'photoPaths'|'events'|'timezone'|'gifts'|'music'>,label:string,max=200)=><label>{label}<input value={content[key]} maxLength={max} onChange={e=>update(key,e.target.value)} autoComplete="off"/></label>;
  const index=tabs.findIndex(t=>t[0]===section);
  const status=!state.online?'Offline · belum tersinkron':state.phase==='saving'?'Menyimpan…':state.phase==='conflict'?'Konflik versi':state.phase==='auth'?'Login diperlukan':state.phase==='recovery'?'Salinan lokal ditemukan':state.pending?'Hasil simpan belum pasti':state.phase==='error'?'Simpan dijeda':dirty?'Perubahan belum tersimpan':state.revision?'Tersimpan di server':'Draft baru';
  return <div className="container workspace editor-workspace">
    <div className="workspace-heading"><div><Link className="back-link" href="/dashboard">← Dashboard</Link><span className="eyebrow">STUDIO UNDANGAN</span><h1>Rangkai hari istimewa.</h1><p>Isian dan desain terpisah. Ganti tema tanpa mengulang cerita Anda.</p></div><div className="editor-save-card"><span className={`save-indicator ${dirty||state.pending?'unsaved':''}`} role="status">{status}</span><small>{state.revision?`Versi server ${state.revision}`:'Belum ada versi server'}{state.updatedAt?` · ${new Date(state.updatedAt).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'})} WIB`:''}</small><button className="button" onClick={()=>void controller.save()} disabled={locked||state.phase==='saving'||state.phase==='conflict'||!state.online}>{state.pending?'Coba simpan kembali':'Simpan sekarang'}</button></div></div>
    <div className="editor-controlbar"><label className="switch-label"><input type="checkbox" checked={autosave} disabled={locked} onChange={e=>setAutosave(e.target.checked)}/><span>Simpan otomatis <strong>{autosave?'aktif':'dijeda'}</strong></span></label><span className="private-label">◇ Draft privat · belum diterbitkan</span><div className="button-row"><button className="button ghost small" onClick={exportBackup}>Unduh salinan JSON</button><button className="button ghost small" disabled={locked||!!state.pending||uploading} onClick={()=>importInput.current?.click()}>Muat salinan</button><input ref={importInput} type="file" hidden accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';void importBackup(file);}}/></div></div>
    <p className="editor-hint">Autosave mengirim setelah Anda berhenti mengetik. Salinan sementara hanya pada sesi tab ini; bukan pengganti backup atau tanda sudah tersimpan di server.</p>
    {state.storageError&&<p role="alert" className="notice error">Penyimpanan sesi browser tidak tersedia. Unduh salinan JSON sebelum menutup tab dan periksa izin penyimpanan browser.</p>}
    {state.message&&state.phase!=='saving'&&<p role="status" className={`notice ${['error','conflict','auth'].includes(state.phase)?'error':''}`}>{state.message}</p>}
    {state.phase==='recovery'&&<div className="notice recovery-box"><strong>Pulihkan pekerjaan pada tab ini?</strong><p>Salinan lokal tidak otomatis menimpa versi server. Foto asli tidak disimpan dalam salinan JSON.</p><div className="button-row"><button className="button small" onClick={()=>controller.restore()}>Pulihkan salinan lokal</button><button className="button ghost small" onClick={()=>{if(window.confirm('Buang salinan lokal dan gunakan versi server?'))controller.discardRecovery();}}>Gunakan versi server</button></div></div>}
    {state.phase==='conflict'&&<div className="notice error"><strong>Versi server berubah atau draft sudah dihapus.</strong><p>Jangan menimpa perubahan dari tab lain. Unduh salinan Anda, lalu muat ulang. Penggabungan dua versi masih dilakukan manual.</p><div className="button-row"><button className="button ghost small" onClick={exportBackup}>Unduh perubahan saya</button><button className="button ghost small" onClick={()=>{if(window.confirm('Pastikan salinan telah diunduh. Buka kembali versi server?')){controller.discardRecovery();window.location.reload();}}}>Muat ulang versi server</button></div></div>}
    {state.phase==='auth'&&<p className="notice error">Unduh salinan sebelum login ulang. <Link href={`/login?next=${encodeURIComponent(state.revision?'/dashboard/undangan/'+id:'/dashboard/baru?template='+theme+'&draft='+id)}`} target="_blank" rel="noopener noreferrer">Buka login di tab lain ↗</Link>. Setelah login sebagai pemilik, muat ulang editor untuk memulihkan salinan.</p>}
    {fileNotice&&<p className="notice" role="status">{fileNotice}</p>}
    <div className="editor-mobile-switch" role="group" aria-label="Tampilan editor"><button className={pane==='form'?'active':''} onClick={()=>setPane('form')}>Edit isian</button><button className={pane==='preview'?'active':''} onClick={()=>setPane('preview')}>Preview langsung</button></div>
    <div className={`studio-grid pane-${pane}`}>
      <section className="studio-edit"><nav className="studio-tabs" aria-label="Langkah editor">{tabs.map(([key,label],i)=><button type="button" key={key} aria-current={section===key?'step':undefined} className={section===key?'active':''} onClick={()=>setSection(key)}><span>{String(i+1).padStart(2,'0')}</span>{label}</button>)}</nav>
      <form className="editor-form panel studio-form" onSubmit={e=>{e.preventDefault();void controller.save();}}><fieldset disabled={locked}>
        <span className="eyebrow">LANGKAH {index+1} DARI {tabs.length}</span>
        {section==='pasangan'&&<><h2>Pasangan & keluarga</h2><p className="muted">Nama yang diisi akan langsung muncul di sampul preview.</p><div className="form-grid">{field('groom','Nama mempelai pria',100)}{field('bride','Nama mempelai wanita',100)}{field('groomParents','Keterangan keluarga pria')}{field('brideParents','Keterangan keluarga wanita')}</div><div className="editor-tip">Sebutkan nama orang tua atau sapaan keluarga sesuai kebutuhan. Kolom keluarga boleh dikosongkan.</div></>}
        {section==='acara'&&<><h2>Acara & lokasi</h2><p className="muted">Maksimal 3 acara. Akad dan resepsi boleh berbeda tanggal, lokasi, dan zona waktu.</p>{events.map((event,i)=><section className="event-editor" key={event.id}><div className="event-editor-heading"><strong>Acara {i+1}{i===0?' · utama':''}</strong><button className="text-button danger-text" type="button" disabled={events.length===1} onClick={()=>removeEvent(i)}>Lepas acara</button></div><label>Nama acara<input value={event.label} maxLength={80} onChange={e=>updateEvent(i,'label',e.target.value)}/></label><label>Tanggal acara<input type="date" value={event.eventDate} onChange={e=>updateEvent(i,'eventDate',e.target.value)} min="2020-01-01" max="9999-12-31"/></label><div className="form-grid"><label>Jam mulai<input type="time" value={event.eventTime} onChange={e=>updateEvent(i,'eventTime',e.target.value)}/></label><label>Jam selesai<input type="time" value={event.endTime} onChange={e=>updateEvent(i,'endTime',e.target.value)}/></label></div><label>Zona waktu<select value={event.timezone} onChange={e=>updateEvent(i,'timezone',e.target.value)}><option value="Asia/Jakarta">WIB — Jakarta</option><option value="Asia/Makassar">WITA — Makassar</option><option value="Asia/Jayapura">WIT — Jayapura</option></select></label><label>Nama gedung / tempat<input value={event.venue} maxLength={200} onChange={e=>updateEvent(i,'venue',e.target.value)}/></label><label>Alamat lengkap<textarea value={event.address} maxLength={500} rows={3} onChange={e=>updateEvent(i,'address',e.target.value)}/></label><EventMapField value={event.mapUrl} venue={event.venue} address={event.address} onChange={value=>updateEvent(i,'mapUrl',value)}/></section>)}<button type="button" className="button ghost" disabled={events.length>=3} onClick={addEvent}>+ Tambah acara</button><p className="editor-hint">Acara pertama menjadi tanggal utama pada sampul. Jam mulai–selesai masing-masing acara masih harus pada hari yang sama.</p></>}
        {section==='cerita'&&<><h2>Sebuah cerita, selamanya.</h2><label>Kalimat pembuka<textarea value={content.opening} maxLength={1000} rows={5} onChange={e=>update('opening',e.target.value)}/><small className="field-count">{content.opening.length}/1.000</small></label><label>Cerita pasangan<textarea value={content.story} maxLength={4000} rows={10} onChange={e=>update('story',e.target.value)} placeholder="Ceritakan pertemuan pertama hingga keputusan melangkah bersama…"/><small className="field-count">{content.story.length}/4.000</small></label><p className="editor-tip">Pisahkan babak cerita dengan baris kosong. Pada Galaxy Night, awali babak dengan tahun, misalnya “2024 — Pertemuan pertama”, untuk tampilan linimasa. Cerita boleh dikosongkan; bagian ini tidak muncul dalam preview ketika kosong.</p></>}
        {section==='galeri'&&<><h2>Kenangan dalam gambar.</h2><p className="muted">{content.photoPaths.length} dari 6 foto. Foto pertama digunakan sebagai sampul. JPEG, PNG, WebP maksimal 5 MB per berkas.</p><label className="upload-area">{uploading?'Memproses foto…':'+ Pilih satu atau beberapa foto'}<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={uploading||content.photoPaths.length>=6||!state.online} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';void upload(files);}}/></label>{uploadNote&&<p className="notice" role="status">{uploadNote}</p>}{photoError&&<div className="notice error">{photoError}<button type="button" className="text-button" onClick={reloadPhotos}>Muat ulang foto</button></div>}<div className="studio-photos">{content.photoPaths.map((path,i)=><article className="studio-photo" key={path}><div className="studio-photo-image">{photos[path]?<img src={photos[path]} alt={`Foto ${i+1}`} referrerPolicy="no-referrer"/>:<span>Foto {i+1}<small>Menunggu gambar</small></span>}<span className="photo-number">{i===0?'Sampul':`0${i+1}`}</span></div><div className="photo-actions"><button type="button" disabled={i===0||uploading} aria-label={`Pindah foto ${i+1} ke kiri`} onClick={()=>update('photoPaths',movePhoto(content.photoPaths,i,i-1))}>←</button><button type="button" disabled={i===content.photoPaths.length-1||uploading} aria-label={`Pindah foto ${i+1} ke kanan`} onClick={()=>update('photoPaths',movePhoto(content.photoPaths,i,i+1))}>→</button><button type="button" disabled={i===0||uploading} onClick={()=>update('photoPaths',movePhoto(content.photoPaths,i,0))}>Sampul</button><button type="button" disabled={uploading} aria-label={`Lepas foto ${i+1} dari draft`} onClick={()=>{if(window.confirm('Lepas foto dari draft? Berkas privat tetap ada di Storage.'))update('photoPaths',content.photoPaths.filter(p=>p!==path));}}>Lepas</button></div></article>)}</div><p className="editor-hint">Foto diperkecil menjadi WebP sebelum diunggah. Melepas foto tidak menghapus berkas asli dari Storage. JSON hanya menyimpan referensi, bukan salinan foto.</p></>}
        {section==='extras'&&<InvitationExtrasEditor content={content} onChange={updateContent}/>}
        {section==='review'&&<><h2>Sentuhan akhir Anda.</h2><label>Desain undangan<select value={theme} onChange={e=>{controller.edit({...state.document,theme:e.target.value});controller.resumeAfterEdit();}}>{themeOptions.map(t=><option value={t.slug} key={t.slug}>{t.name} — {t.active?currency(t.price):'Tidak dijual lagi'}</option>)}</select></label><p className="muted">{chosen.description}</p><div className="review-progress"><div><strong>{done}/{checks.length}</strong><span>bagian terisi</span></div><progress value={done} max={checks.length} aria-label="Kelengkapan isian"/><small>Ini pemeriksaan isian, bukan persetujuan pembayaran atau penerbitan.</small></div><div className="review-checks">{checks.map((check,i)=><button key={i} type="button" onClick={()=>setSection(check.key as Section)}><span aria-hidden>{check.done?'✓':'○'}</span><span>{check.label}<small>{check.required?'Lengkapi sebelum publikasi':'Opsional'}</small></span><span aria-hidden>↗</span></button>)}</div><EventLocationReview events={events} onEdit={()=>setSection('acara')}/><p className="notice">Nama dan harga tema dibaca dari database saat editor dibuka; checkout memeriksa harga terbaru. Tema yang tidak dijual lagi masih bisa dipakai draft lama, tetapi tidak menerima checkout baru. RSVP mengikuti aktivasi. Musik dan rekening hadiah dapat diatur pada bagian Musik & hadiah.</p>{state.revision>0&&!dirty&&!state.pending&&<Link className="button ghost full" href={`/dashboard/undangan/${id}/preview`} target="_blank" rel="noopener noreferrer">Buka preview versi server ↗</Link>}</>}
      </fieldset><div className="editor-step-actions"><button type="button" className="button ghost" disabled={index===0} onClick={()=>setSection(tabs[index-1][0])}>← Sebelumnya</button>{index<tabs.length-1?<button type="button" className="button" onClick={()=>setSection(tabs[index+1][0])}>Berikutnya →</button>:<button className="button" disabled={locked||state.phase==='saving'||state.phase==='conflict'||!state.online} type="submit">Simpan sekarang</button>}</div></form></section>
      <aside className="studio-preview" aria-label="Preview langsung undangan"><div className="preview-heading"><div><span className="eyebrow">LIVE PREVIEW</span><h2>{chosen.name}</h2></div><span className="preview-dot">● Langsung</span></div><label className="preview-guest">Contoh nama tamu<input value={guest} maxLength={100} onChange={e=>setGuest(e.target.value)}/></label><p className="editor-hint">Preview mengikuti formulir, termasuk perubahan yang belum tersimpan. Nama contoh tidak dikirim ke server.</p><div className="preview-phone"><InvitationView embedded template={chosen} content={content} mode="draft" guest={safeGuest(guest)} photoUrls={content.photoPaths.map(path=>photos[path]).filter(Boolean)} coverUrl={photos[content.photoPaths[0]]||''}/></div><div className="preview-footer">◇ Preview privat · perubahan tidak otomatis terbit</div></aside>
    </div>
  </div>;
}
