'use client';
import { useState } from 'react';
import { site } from '@/lib/config';
export default function OrderRequest({invitationId,enabled}:{invitationId:string;enabled:boolean}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[code,setCode]=useState('');
 if(!enabled)return <p className="notice">Pemesanan belum dibuka. Draft dapat disiapkan; admin perlu mengaktifkan permintaan setelah konfigurasi database diverifikasi.</p>;
 if(code)return <div className="notice success" role="status"><strong>Permintaan {code} tersimpan.</strong><p>Admin akan memeriksa data. Ini bukan bukti pembayaran dan undangan belum diterbitkan.</p>{site.whatsapp&&<a className="button small" target="_blank" rel="noopener noreferrer" href={`https://wa.me/${site.whatsapp}?text=${encodeURIComponent('Halo Kastriva, saya ingin menindaklanjuti permintaan undangan '+code+'.')}`}>Hubungi admin via WhatsApp ↗</a>}</div>;
 return <form className="panel order-request" onSubmit={async event=>{event.preventDefault();if(busy)return;const f=new FormData(event.currentTarget);setBusy(true);setError('');try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({invitation_id:invitationId,customer_name:f.get('name'),customer_phone:f.get('phone'),consent:f.get('consent')==='on'})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Permintaan gagal.');setCode(data.order.order_code);}catch(err){setError(err instanceof Error?err.message:'Belum berhasil. Coba lagi dengan data yang sama.');}finally{setBusy(false);}}}><h3>Minta bantuan pengerjaan</h3><p>Tidak ada tagihan atau aktivasi otomatis. Nama pasangan, tanggal, tempat, dan draft harus sudah tersimpan.</p><fieldset disabled={busy}><label>Nama pelanggan<input name="name" autoComplete="name" required minLength={2} maxLength={100}/></label><label>Nomor WhatsApp<input name="phone" type="tel" autoComplete="tel" required maxLength={20} placeholder="08…"/></label><label className="checkbox"><input type="checkbox" name="consent" required/><span>Saya menyetujui data draft dan kontak ini diperiksa admin Kastriva untuk memproses permintaan.</span></label><button className="button" type="submit">{busy?'Mengirim…':'Kirim permintaan pengerjaan'}</button></fieldset>{error&&<p role="alert" className="notice error">{error}</p>}</form>;
}
