import {test,expect} from '@playwright/test';
import {PREMIUM_EDITION_SLUGS} from '../lib/theme-registry';
const categories=['pernikahan','ulang-tahun','aqiqah','acara-kantor'];
const names=['Seraphine Garden','Jubilee Carousel','Nur Eden','Nocturne Gala'];
for(const [index,slug] of PREMIUM_EDITION_SLUGS.entries())test(`premium edition artwork and interactions: ${slug}`,async({page,isMobile})=>{
 if(isMobile)await page.setViewportSize({width:390,height:844});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`/tema?category=${categories[index]}`);
 const card=page.locator('.theme-card').filter({has:page.getByRole('heading',{name:names[index],exact:true})});
 await expect(card.locator('.premium-collection-badge')).toHaveText('PREMIUM COLLECTION');
 await card.getByRole('link',{name:/Lihat demo/}).click();
 const demo=page.frameLocator('.demo-device-content');
 const root=demo.locator('.invitation');await expect(root).toHaveAttribute('data-inv-hydrated','true');
 await page.evaluate(()=>document.fonts.ready.then(()=>undefined));
 await expect(demo.locator('.cover-frame .premium-frame-art')).toHaveAttribute('data-premium-edition-art',slug);
 await expect(demo.locator('.cover-frame .premium-frame-corner')).toHaveCount(2);
 await expect(demo.locator('.inv-cover .inv-names')).toHaveAccessibleName(index===0?'Ahmad & Siti':index===1?'Aruna':index===2?'Bayi Aruna':'Annual Gathering');
 await demo.getByRole('button',{name:/Buka undangan/}).click();
 await expect(root).toHaveAttribute('data-inv-opening-state','open');
 await expect(demo.locator('.inv-auto-scroll')).toHaveAttribute('data-scroll-state','running');
 await expect(demo.locator('.music-toggle')).toHaveAttribute('aria-pressed','true');
 await demo.locator('.inv-auto-scroll button').click();
 await expect(demo.locator('.inv-auto-scroll')).toHaveAttribute('data-scroll-state','paused');
 await expect(demo.locator('.inv-hero .inv-framed-photo')).toHaveCSS('object-fit','contain');
 const event=demo.locator('.event-box').first();await event.scrollIntoViewIfNeeded();
 await expect(event).toHaveAttribute('data-inv-card-state','shown');
 const wishes=demo.locator('.inv-demo-wish-list');await wishes.scrollIntoViewIfNeeded();await expect(wishes).toBeVisible();
 if(index===0)await expect(demo.locator('.gift-disclosure')).toHaveCount(1);
 if(isMobile)await page.setViewportSize({width:320,height:740});
 expect(await root.evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);
 await page.emulateMedia({reducedMotion:'reduce'});
 await expect(demo.locator('.inv-ornament-corner').first()).toHaveCSS('animation-name','none');
 expect(errors).toEqual([]);
});
