import {test,expect} from '@playwright/test';
import {OCCASION_THEME_SLUGS} from '../lib/theme-registry';
const categories=['pernikahan','ulang-tahun','aqiqah','acara-kantor'];
const names=['Velvet Vow','Peach Confetti','Little Moon','Sapphire Summit'];
for(const [index,slug] of OCCASION_THEME_SLUGS.entries())test(`occasion collection is discoverable and interactive: ${slug}`,async({page,isMobile})=>{
 if(isMobile)await page.setViewportSize({width:390,height:844});
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(`/tema?category=${categories[index]}`);
 const card=page.locator('.theme-card').filter({has:page.getByRole('heading',{name:names[index],exact:true})});
 await expect(card).toHaveCount(1);
 await card.getByRole('link',{name:/Lihat demo/}).click();
 const root=page.locator('.invitation');
 await expect(root).toHaveAttribute('data-inv-hydrated','true');
 await page.evaluate(()=>document.fonts.ready.then(()=>undefined));
 await expect(page.locator('.inv-cover [data-occasion-art]')).toHaveAttribute('data-occasion-art',slug);
 await expect(page.locator('.inv-cover .inv-names')).toHaveAccessibleName(index===0?'Ahmad & Siti':index===1?'Aruna':index===2?'Bayi Aruna':'Annual Gathering');
 await page.getByRole('button',{name:/Buka undangan/}).click();
 await expect(root).toHaveAttribute('data-inv-opening-state','open');
 await expect(page.locator('.inv-auto-scroll')).toHaveAttribute('data-scroll-state','running');
 await expect(page.locator('.music-toggle')).toHaveAttribute('aria-pressed','true');
 await page.locator('.inv-auto-scroll button').click();
 await expect(page.locator('.inv-auto-scroll')).toHaveAttribute('data-scroll-state','paused');
 await expect(page.locator('.inv-hero .inv-framed-photo')).toHaveCSS('object-fit','contain');
 const event=page.locator('.event-box').first();await event.scrollIntoViewIfNeeded();
 await expect(event).toHaveAttribute('data-inv-card-state','shown');
 const wishes=page.locator('.inv-demo-wish-list');await wishes.scrollIntoViewIfNeeded();await expect(wishes).toBeVisible();
 if(slug==='velvet-vow')await expect(page.locator('.gift-disclosure')).toHaveCount(1);
 if(isMobile)await page.setViewportSize({width:320,height:740});
 expect(await root.evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);
 await page.emulateMedia({reducedMotion:'reduce'});
 await expect(page.locator('.occasion-corner').first()).toHaveCSS('animation-name','none');
 expect(errors).toEqual([]);
});
