import {test,expect} from '@playwright/test';
import {APP_VERSION} from '../lib/release';
import {ALL_THEME_SLUGS} from '../lib/theme-registry';
let pageErrors:string[]=[];
test.beforeEach(async({page})=>{pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));await page.emulateMedia({reducedMotion:'reduce'});});
test.afterEach(async()=>{expect(pageErrors).toEqual([]);});
test('health never attests live backend',async({request})=>{const r=await request.get('/api/health');expect(r.ok()).toBe(true);expect(await r.json()).toMatchObject({version:APP_VERSION,backendConnectionVerified:false,productionReadinessVerified:false});expect(r.headers()['cache-control']).toContain('no-store');});
for(const route of ['/','/tema','/harga','/panduan','/setup','/login'])test('actual rendered route '+route,async({page})=>{await page.goto(route);await expect(page.locator('main')).toBeVisible();await expect(page.locator('h1').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);});
test('mobile menu opens, navigates, closes',async({page,isMobile})=>{test.skip(!isMobile,'Mobile-specific navigation');await page.goto('/');await page.getByRole('button',{name:'Buka menu',exact:true}).click();await page.getByRole('navigation',{name:'Navigasi ponsel'}).getByRole('link',{name:'Koleksi tema'}).click();await expect(page).toHaveURL(/\/tema$/);await expect(page.getByRole('navigation',{name:'Navigasi ponsel'})).toHaveCount(0);});
for(const slug of ALL_THEME_SLUGS)test('demo opens with actual React '+slug,async({page})=>{
 await page.goto('/demo/'+slug+'?to=Undangan%20Uji');
 const frame=page.locator('.demo-device-content'),demo=frame.contentFrame();
 await expect(frame).toHaveAttribute('title',/^Demo mobile /);
 await expect(demo.getByText('Undangan Uji',{exact:true})).toBeVisible();
 expect(await demo.locator('html').evaluate(el=>el.ownerDocument.defaultView!.innerWidth)).toBeLessThanOrEqual(480);
 await demo.getByRole('button',{name:/Buka undangan/}).click();
 await expect(demo.locator('.inv-content')).toBeVisible();
 await expect(demo.getByRole('heading',{name:/^Waktu & tempat/}).first()).toBeAttached();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('demo RSVP explicitly local, escaped and cleared after reload',async({page})=>{await page.goto('/demo/elegant-rose');const demo=page.frameLocator('.demo-device-content');await demo.getByRole('button',{name:/Buka undangan/}).click();await expect(demo.locator('.inv-content')).toBeVisible();const form=demo.locator('form.rsvp-form');await expect(form).toBeAttached();await form.evaluate(el=>el.scrollIntoView({block:'center'}));await form.locator('input[name="name"]').fill('<img src=x onerror=alert(1)>');await form.locator('select[name="attendance"]').selectOption('hadir',{force:true});await form.locator('textarea[name="message"]').fill('DATA UJI BUKAN RSVP NYATA');await form.getByRole('button',{name:'Coba simulasi RSVP'}).click();await expect(demo.getByText('DATA UJI BUKAN RSVP NYATA',{exact:true})).toBeVisible();await expect(demo.locator('.wish-card img')).toHaveCount(0);await page.reload();await demo.getByRole('button',{name:/Buka undangan/}).click();await expect(demo.locator('[data-demo-response]')).toHaveCount(0);await expect(demo.locator('[data-demo-wish]')).toHaveCount(3);});
test('admin cannot be opened without configured authentication',async({page})=>{await page.goto('/admin/rilis');await expect(page).toHaveURL(/\/setup$/);});
test('cross-origin public mutation rejected before a feature/backend call',async({request})=>{const r=await request.post('/api/public/valid-slug/respond',{headers:{origin:'https://evil.invalid'},data:{}});expect(r.status()).toBe(403);});
test('public feature stays closed in isolated demo',async({request})=>{const r=await request.post('/api/public/valid-slug/respond',{headers:{origin:'http://127.0.0.1:3000'},data:{}});expect(r.status()).toBe(503);});
test('legacy personal-data endpoint remains gone',async({request})=>{const r=await request.get('/api/guests/test');expect(r.status()).toBe(410);});
