import type { DraftContent } from './types.ts';
import {completeGift} from './invitation-extras.ts';
import { asRecord, UUID, ValidationError, invitationEvents, parseDraft } from './domain.ts';
export const SALE_STATES = ['awaiting_payment','awaiting_review','rejected','paid','cancelled','revoked'] as const;
export type SaleState = typeof SALE_STATES[number];
export const SALE_LABEL: Record<SaleState,string> = {awaiting_payment:'Menunggu pembayaran',awaiting_review:'Menunggu verifikasi',rejected:'Konfirmasi ditolak',paid:'Pembayaran terverifikasi',cancelled:'Dibatalkan',revoked:'Akses dicabut'};
export type CommerceSettings = {id:number;revision:number;checkout_enabled:boolean;publishing_enabled:boolean;active_days:number;bank_name:string;bank_account:string;bank_holder:string;instructions:string};
export type Sale = {id:string;owner_id:string;invitation_id:string;order_code:string;theme_slug:string;theme_name:string;total_price:number;active_days:number;payment_details:{bank_name:string;bank_account:string;bank_holder:string;instructions:string};customer_name:string;customer_phone:string;customer_email:string;status:SaleState;revision:number;created_at:string;updated_at:string;paid_at:string|null;expires_at:string|null;payment_reference:string;admin_note:string};
export type Publication = {sale_id:string;owner_id:string;slug:string;theme_slug:string;content:DraftContent;draft_revision:number;revision:number;active:boolean;created_at:string;updated_at:string};
export type SaleEvent = {id:number;sale_id:string;action:string;old_status:string;new_status:string;note:string;created_at:string};
export const PUBLIC_SLUG=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const RESERVED=new Set(['admin','api','auth','dashboard','demo','login','setup','tema','harga','kastriva','undangan','null','undefined']);
export function parseSlug(v:unknown):string{if(typeof v!=='string'||v.length<5||v.length>64||!PUBLIC_SLUG.test(v)||RESERVED.has(v))throw new ValidationError('Alamat undangan: 5–64 huruf kecil/angka, dipisahkan tanda minus; tidak boleh nama sistem.');return v;}
export function requireKeys(x:Record<string,unknown>,keys:readonly string[]){if(Object.keys(x).some(k=>!keys.includes(k))||keys.some(k=>!Object.hasOwn(x,k)))throw new ValidationError('Kolom permintaan tidak sesuai.');}
function text(v:unknown,min:number,max:number,label:string){if(typeof v!=='string'||v.trim().length<min||v.trim().length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(v))throw new ValidationError(label+' tidak valid.');return v.trim();}
function uuid(v:unknown){if(typeof v!=='string'||!UUID.test(v))throw new ValidationError('Identitas permintaan tidak valid.');return v;}
function int(v:unknown,min:number,max=2147483647){if(typeof v!=='number'||!Number.isSafeInteger(v)||v<min||v>max)throw new ValidationError('Angka / versi tidak valid.');return v;}
export function readyToPublish(content:DraftContent):string[]{const errors:string[]=[];if(!content.groom.trim()||!content.bride.trim())errors.push('Lengkapi nama kedua mempelai.');for(const [i,e] of invitationEvents(content).entries()){if(!e.eventDate||!e.venue.trim()||!e.address.trim()||!e.label.trim())errors.push(`Lengkapi tanggal, nama acara, tempat, dan alamat acara ${i+1}.`);}for(const [i,gift] of (content.gifts||[]).entries()){if(!completeGift(gift))errors.push(`Lengkapi bank, nomor (5–30 angka), dan pemilik rekening hadiah ${i+1}, atau hapus rekening tersebut.`);}return errors;}
export function parseCheckout(value:unknown){const x=asRecord(value);requireKeys(x,['invitation_id','draft_revision','theme','quoted_price','quoted_days','settings_revision','customer_name','customer_phone','request_id']);const phone=text(x.customer_phone,10,15,'WhatsApp');if(!/^62\d{8,13}$/.test(phone))throw new ValidationError('WhatsApp harus berformat 628… tanpa +.');return {invitation_id:uuid(x.invitation_id),draft_revision:int(x.draft_revision,1),theme:text(x.theme,1,60,'Tema'),quoted_price:int(x.quoted_price,1),quoted_days:int(x.quoted_days,1,730),settings_revision:int(x.settings_revision,1),customer_name:text(x.customer_name,2,100,'Nama'),customer_phone:phone,request_id:uuid(x.request_id)};}
export const SALE_ACTIONS=['submit_payment','approve','reject','cancel','revoke'] as const;
export type SaleAction=typeof SALE_ACTIONS[number];
export function canAct(state:SaleState,action:SaleAction,admin:boolean){return action==='submit_payment'?['awaiting_payment','rejected'].includes(state):action==='approve'||action==='reject'?admin&&state==='awaiting_review':action==='revoke'?admin&&state==='paid':admin?['awaiting_payment','awaiting_review','rejected'].includes(state):['awaiting_payment','rejected'].includes(state);}
export function parseSaleAction(value:unknown,admin=false){const x=asRecord(value);requireKeys(x,['sale_id','action','revision','request_id','note','reference','received_amount','verified']);if(!SALE_ACTIONS.includes(x.action as SaleAction))throw new ValidationError('Tindakan tidak dikenal.');const action=x.action as SaleAction;if(!admin&&['approve','reject','revoke'].includes(action))throw new ValidationError('Tindakan khusus admin.');const reference=text(x.reference,action==='submit_payment'||action==='approve'?3:0,160,'Referensi transfer');const note=text(x.note,['reject','revoke'].includes(action)?5:0,500,'Catatan');if(typeof x.verified!=='boolean')throw new ValidationError('Pernyataan verifikasi tidak valid.');const amount=int(x.received_amount,0);if(action==='approve'&&(!x.verified||amount<=0))throw new ValidationError('Cocokkan mutasi rekening dan jumlah yang benar-benar diterima.');if(action!=='approve'&&(amount!==0||x.verified!==false))throw new ValidationError('Jumlah/verifikasi hanya untuk persetujuan admin.');return {sale_id:uuid(x.sale_id),action,revision:int(x.revision,1),request_id:uuid(x.request_id),note,reference,received_amount:amount,verified:x.verified};}
export function parsePublication(value:unknown){const x=asRecord(value);requireKeys(x,['sale_id','action','slug','draft_revision','publication_revision','request_id','consent']);if(x.action!=='publish'&&x.action!=='unpublish')throw new ValidationError('Tindakan publikasi tidak valid.');if(typeof x.consent!=='boolean'||(x.action==='publish'&&!x.consent))throw new ValidationError('Persetujuan menampilkan data dan foto kepada publik diperlukan.');return {sale_id:uuid(x.sale_id),action:x.action,slug:parseSlug(x.slug),draft_revision:int(x.draft_revision,1),publication_revision:int(x.publication_revision,0),request_id:uuid(x.request_id),consent:x.consent};}
export function parseCommerceSettings(value:unknown){const x=asRecord(value);requireKeys(x,['revision','checkout_enabled','publishing_enabled','active_days','bank_name','bank_account','bank_holder','instructions']);if(typeof x.checkout_enabled!=='boolean'||typeof x.publishing_enabled!=='boolean')throw new ValidationError('Status pengaturan harus boolean.');const result={revision:int(x.revision,1),checkout_enabled:x.checkout_enabled,publishing_enabled:x.publishing_enabled,active_days:int(x.active_days,1,730),bank_name:text(x.bank_name,0,80,'Bank'),bank_account:text(x.bank_account,0,50,'Rekening'),bank_holder:text(x.bank_holder,0,120,'Pemilik rekening'),instructions:text(x.instructions,0,1500,'Petunjuk')};if(result.checkout_enabled&&(!result.bank_name||!/^\d[\d -]{3,48}\d$/.test(result.bank_account)||!result.bank_holder))throw new ValidationError('Isi rekening penerima yang benar sebelum membuka checkout.');return result;}
export function publicationAvailable(sale:Pick<Sale,'status'|'expires_at'>,pub:Pick<Publication,'active'>|null,enabled:boolean,now:number){const expiry=Date.parse(sale.expires_at||'');return enabled&&sale.status==='paid'&&pub?.active===true&&Number.isFinite(expiry)&&expiry>now;}
export function publicPhotoIndex(v:string){if(!/^[0-5]$/.test(v))throw new ValidationError('Foto tidak ditemukan.');return Number(v);}
export function parsePublicInvitation(value:unknown){const x=asRecord(value);requireKeys(x,['slug','theme_slug','content','photo_count','revision','expires_at']);const content=asRecord(x.content);if(!Array.isArray(content.photoPaths)||content.photoPaths.length)throw new ValidationError('Referensi foto privat tidak boleh masuk respons publik.');const cleaned=parseDraft(content,'00000000-0000-4000-8000-000000000000');if(typeof x.expires_at!=='string'||!Number.isFinite(Date.parse(x.expires_at)))throw new ValidationError('Masa aktif tidak valid.');return {slug:parseSlug(x.slug),theme_slug:text(x.theme_slug,1,60,'Tema'),content:cleaned,photo_count:int(x.photo_count,0,6),revision:int(x.revision,1),expires_at:x.expires_at};}
export function shareUrl(origin:string,slug:string,guest=''){const url=new URL('/u/'+parseSlug(slug),origin);if(!['https:','http:'].includes(url.protocol))throw new ValidationError('Alamat situs tidak valid.');const safe=guest.trim().slice(0,100);if(safe)url.searchParams.set('to',safe);return url.toString();}
export function saleTimestamp(v:string|null){return v?new Date(v).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})+' WIB':'—';}
