import {categoryForTheme,fieldsForCategory} from './invitation-category.ts';
import {weddingMusic} from './theme-music.ts';
import { asRecord, parseDraft, parseSave, blankContent, invitationEvents, withEvents, validDate, safeMapHref, UUID, ValidationError } from './domain.ts';
import type { DraftContent } from './types.ts';
export type EditorDocument = { theme: string; content: DraftContent };
export type SavePayload = ReturnType<typeof parseSave>;
export type PendingSave = { payload: SavePayload; document: EditorDocument };
export type EditorJournal = {
  format: 'kastriva-editor-session'; version: 1; owner: string; id: string;
  document: EditorDocument; revision: number; savedDocument: EditorDocument | null;
  pending: PendingSave | null; timestamp: number;
};
import {WEDDING_THEME_SLUGS} from './theme-registry.ts';
export const WEDDING_SLUGS = WEDDING_THEME_SLUGS;
export function editableDocument(content: DraftContent, theme: string): EditorDocument {
  return {theme,content:withEvents(structuredClone(content),invitationEvents(content,categoryForTheme(theme)))};
}
export function documentKey(document: EditorDocument | null): string { return JSON.stringify(document); }
export function parseDocument(value: unknown, owner: string, editing = false): EditorDocument {
  const x = asRecord(value);
  if (Object.keys(x).some(key => !['theme','content'].includes(key)) || typeof x.theme !== 'string' || !categoryForTheme(x.theme)) throw new ValidationError('Tema pada salinan tidak didukung.');
  const parsed = parseDraft(x.content,owner,editing);
  if(categoryForTheme(x.theme)!=='pernikahan' && (parsed.bride || parsed.brideParents)) throw new ValidationError('Kategori ini hanya memakai satu nama utama. Kosongkan kolom mempelai wanita dan keluarganya.');
  return {theme:x.theme,content:editing ? structuredClone(x.content) as DraftContent : parsed};
}
export function sessionKey(owner: string, id: string): string { return `ki-editor:v3:${owner}:${id}`; }
/** Local copies are untrusted input, even when generated by this app. No tokens/media URLs. */
export function readJournal(raw: string, owner: string, id: string): EditorJournal {
  if (raw.length > 256 * 1024) throw new ValidationError('Salinan lokal terlalu besar.');
  const x = asRecord(JSON.parse(raw));
  if (x.format !== 'kastriva-editor-session' || x.version !== 1 || x.owner !== owner || x.id !== id || !UUID.test(owner) || !UUID.test(id)) throw new ValidationError('Salinan bukan milik akun atau draft ini.');
  if (!Number.isSafeInteger(x.revision) || Number(x.revision) < 0 || !Number.isFinite(x.timestamp)) throw new ValidationError('Versi salinan lokal tidak valid.');
  const document = parseDocument(x.document,owner,true), savedDocument = x.savedDocument === null ? null : parseDocument(x.savedDocument,owner,true);
  let pending: PendingSave | null = null;
  if (x.pending !== null) {
    const job = asRecord(x.pending), payload = parseSave(job.payload,owner), captured = parseDocument(job.document,owner,true);
    if (payload.id !== id || payload.expected_revision !== x.revision || payload.theme_slug !== captured.theme || JSON.stringify(payload.content) !== JSON.stringify(parseDraft(captured.content,owner))) throw new ValidationError('Permintaan tertunda tidak sesuai salinan.');
    pending = {payload,document:captured};
  }
  return {format:'kastriva-editor-session',version:1,owner,id,document,revision:Number(x.revision),savedDocument,pending,timestamp:Number(x.timestamp)};
}
export function createBackup(document: EditorDocument, owner: string): string {
  return JSON.stringify({format:'kastriva-invitation-backup',version:1,ownerId:owner,exportedAt:new Date().toISOString(),...document},null,2);
}
export function readBackup(raw: string, owner: string): EditorDocument {
  if (raw.length > 128 * 1024) throw new ValidationError('Ukuran salinan maksimal 128 KB.');
  const x = asRecord(JSON.parse(raw));
  const legacy = x.format === undefined && Object.keys(x).every(key => ['theme','content'].includes(key));
  if (!legacy && (x.format !== 'kastriva-invitation-backup' || x.version !== 1 || x.ownerId !== owner || Object.keys(x).some(k => !['format','version','ownerId','exportedAt','theme','content'].includes(k)))) throw new ValidationError('Format salinan tidak didukung atau akun tidak sesuai.');
  const d = parseDocument({theme:x.theme,content:x.content},owner,true);
  return editableDocument(d.content,d.theme);
}
export function completion(content: DraftContent, category = 'pernikahan') {
  const events = invitationEvents(content,category);
  return [
    {key:'pasangan',label:category==='pernikahan'?'Nama kedua mempelai':fieldsForCategory(category).name,done:!!content.groom.trim() && (category!=='pernikahan'||!!content.bride.trim()),required:true},
    {key:'acara',label:'Nama dan tanggal setiap acara',done:events.every(e => !!e.label.trim() && validDate(e.eventDate)),required:true},
    {key:'acara',label:'Jam dan tempat setiap acara',done:events.every(e => /^([01]\d|2[0-3]):[0-5]\d$/.test(e.eventTime) && /^([01]\d|2[0-3]):[0-5]\d$/.test(e.endTime) && e.endTime>e.eventTime && !!e.venue.trim()),required:true},
    {key:'acara',label:'Alamat lengkap setiap acara',done:events.every(e => !!e.address.trim()),required:true},
    {key:'acara',label:'Link Maps setiap acara',done:events.every(e => !!safeMapHref(e.mapUrl)),required:false},
    {key:'cerita',label:'Kalimat pembuka dan cerita',done:!!content.opening.trim() && !!content.story.trim(),required:false},
    {key:'galeri',label:'Foto sampul dan galeri',done:content.photoPaths.length>0,required:false},
  ];
}
export function movePhoto(paths: string[], from: number, to: number): string[] {
  if (![from,to].every(n => Number.isInteger(n) && n>=0 && n<paths.length)) return paths;
  const next = [...paths]; const [path] = next.splice(from,1); next.splice(to,0,path); return next;
}

export function blankContentForTheme(theme:string):DraftContent {
  return {...blankContent,opening:fieldsForCategory(categoryForTheme(theme)||'pernikahan').opening,photoPaths:[],...(weddingMusic(theme)?{music:'theme' as const,musicVolume:45}:{})};
}
