/** AUTO-GENERATED by tools/import_music/identify_and_import.py. Do not hand-edit. */
export const IMPORTED_MUSIC_TRACKS = [
  {
    "id": "wedding-01",
    "name": "Infinite Pease",
    "artist": "Novo Talos & Julius Aston",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-01.mp3"
  },
  {
    "id": "wedding-02",
    "name": "Dia",
    "artist": "Anji",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-02.mp3"
  },
  {
    "id": "wedding-04",
    "name": "Clear Your Mind",
    "artist": "EasySleepMusic",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-04.mp3"
  },
  {
    "id": "wedding-05",
    "name": "For the Rest of My Life",
    "artist": "Maher Zain",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-05.mp3"
  },
  {
    "id": "wedding-06",
    "name": "Tuhan Jagakan Dia (Remix)",
    "artist": "Restikha Buleleng",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-06.mp3"
  },
  {
    "id": "wedding-07",
    "name": "Uso Wangu",
    "artist": "Emmanuel Mgogo",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-07.mp3"
  },
  {
    "id": "wedding-08",
    "name": "Like Im Gonna Lose You (Originally Performed by Meghan Trainor and John Legend) [Karaoke Instrumental]",
    "artist": "Doc Holiday",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-08.mp3"
  },
  {
    "id": "wedding-09",
    "name": "A Whole New World (End Title)",
    "artist": "ZAYN & Zhavia",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-09.mp3"
  },
  {
    "id": "wedding-11",
    "name": "Bukti",
    "artist": "Virgoun",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-11.mp3"
  },
  {
    "id": "wedding-12",
    "name": "Relaxing Ballad",
    "artist": "Alexander Nakarada",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-12.mp3"
  },
  {
    "id": "wedding-18",
    "name": "Menunggu Kamu (From \"Jelita Sejuba\")",
    "artist": "Anji",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-18.mp3"
  },
  {
    "id": "wedding-19",
    "name": "Baraka Allahu Lakuma (Percussion Version)",
    "artist": "Maher Zain",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-19.mp3"
  },
  {
    "id": "wedding-21",
    "name": "Janji Suci",
    "artist": "Yovie & Nuno",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-21.mp3"
  },
  {
    "id": "wedding-25",
    "name": "10,000 Hours",
    "artist": "Dan + Shay & Justin Bieber",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-25.mp3"
  },
  {
    "id": "wedding-27",
    "name": "Hanya Rindu",
    "artist": "Andmesh",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-27.mp3"
  },
  {
    "id": "wedding-29",
    "name": "Hanya Rindu",
    "artist": "Emma Heesters",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-29.mp3"
  },
  {
    "id": "wedding-30",
    "name": "Dari Mata",
    "artist": "Jaz",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-30.mp3"
  },
  {
    "id": "wedding-31",
    "name": "Rabbee Yebarik (Arabic Version)",
    "artist": "Maher Zain",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-31.mp3"
  },
  {
    "id": "wedding-32",
    "name": "The Way You Look At Me (Acoustic)",
    "artist": "Christian Bautista",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-32.mp3"
  },
  {
    "id": "wedding-34",
    "name": "Surat Cinta Untuk Starla",
    "artist": "Virgoun",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-34.mp3"
  },
  {
    "id": "wedding-35",
    "name": "Perfect",
    "artist": "Ed Sheeran",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-35.mp3"
  },
  {
    "id": "wedding-36",
    "name": "Cinta Luar Biasa",
    "artist": "Andmesh",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-36.mp3"
  },
  {
    "id": "wedding-37",
    "name": "Beautiful in White",
    "artist": "Divine Destiny",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-37.mp3"
  },
  {
    "id": "wedding-38",
    "name": "Karena Kamu Cuma Satu",
    "artist": "Naif",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-38.mp3"
  },
  {
    "id": "wedding-39",
    "name": "Love Story",
    "artist": "Anthony Ventura",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-39.mp3"
  },
  {
    "id": "wedding-42",
    "name": "Can't Help Falling In Love",
    "artist": "Clever Lopez",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-42.mp3"
  },
  {
    "id": "wedding-43",
    "name": "Istikharah Cinta",
    "artist": "Sigma",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-43.mp3"
  },
  {
    "id": "wedding-44",
    "name": "When God Made You",
    "artist": "NewSong",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-44.mp3"
  },
  {
    "id": "wedding-45",
    "name": "Bidadari Tak Bersayap",
    "artist": "Anji",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-45.mp3"
  },
  {
    "id": "wedding-49",
    "name": "Beautiful In White",
    "artist": "Shane Filan",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-49.mp3"
  },
  {
    "id": "wedding-50",
    "name": "Nyaman",
    "artist": "Andmesh",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-50.mp3"
  },
  {
    "id": "wedding-51",
    "name": "Hasbi Rabbi",
    "artist": "Sami Yusuf",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-51.mp3"
  },
  {
    "id": "wedding-52",
    "name": "Marry Your Daughter",
    "artist": "BRKNRBTZ",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-52.mp3"
  },
  {
    "id": "wedding-56",
    "name": "Melamarmu",
    "artist": "Badai Romantic Project",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-56.mp3"
  },
  {
    "id": "wedding-61",
    "name": "Spring",
    "artist": "Ratzu",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-61.mp3"
  },
  {
    "id": "wedding-63",
    "name": "Kumau Dia",
    "artist": "Andmesh",
    "mood": "Pop Indonesia · Pernikahan",
    "detail": "Koleksi MP3 pernikahan yang diimpor pengelola.",
    "kind": "file",
    "group": "wedding",
    "src": "/music/imported/wedding-63.mp3"
  },
  {
    "id": "aqiqah-01",
    "name": "Buah Hati",
    "artist": "Armada",
    "mood": "Aqiqah",
    "detail": "Koleksi MP3 aqiqah yang diimpor pengelola.",
    "kind": "file",
    "group": "aqiqah",
    "src": "/music/imported/aqiqah-01.mp3"
  },
  {
    "id": "aqiqah-02",
    "name": "What A Wonderful World",
    "artist": "Louis Armstrong",
    "mood": "Aqiqah",
    "detail": "Koleksi MP3 aqiqah yang diimpor pengelola.",
    "kind": "file",
    "group": "aqiqah",
    "src": "/music/imported/aqiqah-02.mp3"
  }
] as const;
