/**
 * AUTO-GENERATED by tools/import_music/identify_and_import.py.
 * Empty by default so the application still builds before local song recognition.
 * Do not hand-edit after running the importer.
 */
export const IMPORTED_MUSIC_TRACKS = [] as const;
