import Link from 'next/link';
import { requireAdmin } from '@/lib/server-auth';
import type { Order } from '@/lib/types';
import { currency } from '@/lib/domain';
import OrderStatus from '@/components/OrderStatus';
import LogoutButton from '@/components/LogoutButton';
export const dynamic='force-dynamic';
export const metadata={title:'Admin',robots:{index:false,follow:false}};
export default async function Admin({searchParams}:{searchParams:Promise<{page?:string}>}){const{db}=await requireAdmin();const params=await searchParams;const page=Math.max(1,Math.min(10000,Number.parseInt(params.page||'1',10)||1));const{data,error,count}=await db.from('ki_orders').select('*',{count:'exact'}).order('created_at',{ascending:false}).range((page-1)*20,page*20-1);return <main className="container workspace"><div className="workspace-heading"><div><span className="eyebrow">PENGELOLAAN PERMINTAAN</span><h1>Dashboard Kastriva.</h1><p>{count??'—'} permintaan tercatat · halaman {page}</p></div><div className="button-row"><Link className="button ghost small" href="/admin/sistem">Status sistem</Link><Link className="button ghost small" href="/panduan">Panduan</Link><Link className="button ghost small" href="/dashboard">Akun saya</Link><LogoutButton/></div></div><div className="notice">Admin versi ini memeriksa permintaan pengerjaan. Tidak ada tombol penetapan lunas atau penerbitan. Harga di bawah bukan pendapatan.</div>{error?<p className="notice error">Data admin gagal dimuat. Periksa SQL dan role admin; data tidak dianggap kosong.</p>:!data?.length?<div className="empty-state"><h2>Belum ada permintaan di halaman ini.</h2><p>Permintaan muncul setelah pelanggan menyimpan draft dan mengirim permintaan pengerjaan.</p></div>:<div className="admin-orders">{(data as Order[]).map(o=><article className="panel admin-order" key={o.id}><div><span className="eyebrow">{o.order_code}</span><h2>{[o.snapshot.groom,o.snapshot.bride].filter(Boolean).join(' & ')}</h2><p>{o.theme_slug} · {currency(o.total_price)} (referensi)</p><p>{o.customer_name}<br/>{o.customer_email}<br/>{o.customer_phone}</p><details><summary>Detail acara yang diajukan</summary><p>{o.snapshot.eventDate} · {o.snapshot.eventTime}–{o.snapshot.endTime} · {o.snapshot.timezone}</p><p>{o.snapshot.venue}<br/>{o.snapshot.address}</p><p className="pre-line">{o.snapshot.story}</p></details></div><OrderStatus id={o.id} status={o.status}/></article>)}</div>}<div className="button-row">{page>1&&<Link className="button ghost" href={'/admin/permintaan?page='+(page-1)}>← Sebelumnya</Link>}{(count||0)>page*20&&<Link className="button ghost" href={'/admin/permintaan?page='+(page+1)}>Berikutnya →</Link>}</div></main>;}
