'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {CMS_TEXT_LIMITS,restoreCmsDocument,parseCmsDocument,parseCmsAck,cmsBackup,readCmsBackup,encodeCmsPending,decodeCmsPending,type CmsState,type CmsTextKey,type CmsDocument,type CmsCommand} from '@/lib/cms';
import {templates} from '@/lib/templates';
import {guestRequest} from '@/lib/guest-transport';
import {useRetainedRequest} from '@/components/guests/useRetainedRequest';
import MarketingHome from './MarketingHome';
const sections=[['hero','Hero'],['tentang','Tentang & keunggulan'],['alur','Koleksi & cara kerja'],['faq','FAQ'],['cta','CTA'],['kontak','Brand & kontak'],['seo','SEO'],['katalog','Tema & harga'],['riwayat','Riwayat']] as const;
type Section=typeof sections[number][0];
export default function CmsEditor({initial,owner}:{initial:CmsState;owner:string}){
 const router=useRouter(),[document,setDocument]=useState(initial.draft),[section,setSection]=useState<Section>('hero'),[preview,setPreview]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState(false),[waiting,setWaiting]=useState(false);const importRef=useRef<HTMLInputElement>(null),expected=useRef(0);
 const m=useRetainedRequest<CmsCommand,ReturnType<typeof parseCmsAck>>({storageKey:'ki:cms:v1:'+owner,decode:raw=>decodeCmsPending(raw,owner),encode:x=>encodeCmsPending(owner,x),send:x=>guestRequest('/api/admin/cms',x,v=>parseCmsAck(v,x)),onSuccess:ack=>{expected.current=ack.revision;setWaiting(true);router.refresh();}});
 useEffect(()=>{if(initial.revision>=expected.current){setDocument(initial.draft);setChecked(false);setWaiting(false);}},[initial]);
 const dirty=JSON.stringify(document)!==JSON.stringify(initial.draft),locked=m.locked||waiting;
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[dirty]);
 function edit(next:CmsDocument){setDocument(next);setChecked(false);setError('');}
 function text(key:CmsTextKey,label:string,multi=false){const value=document.content[key];return <label key={key}>{label}{multi?<textarea rows={key==='heroTitle'?2:3} maxLength={CMS_TEXT_LIMITS[key][1]} value={value} onChange={e=>edit({...document,content:{...document.content,[key]:e.target.value}})}/>:<input maxLength={CMS_TEXT_LIMITS[key][1]} value={value} onChange={e=>edit({...document,content:{...document.content,[key]:e.target.value}})}/>}<small>{value.length}/{CMS_TEXT_LIMITS[key][1]}</small></label>;}
 function load(doc:CmsDocument,label:string){if(locked)return;if(dirty&&!window.confirm('Ganti perubahan yang belum disimpan? Unduh salinan dahulu bila diperlukan.'))return;edit(structuredClone(restoreCmsDocument(doc,initial.live.catalog)));setError(label+' dimuat ke formulir, belum disimpan atau diterbitkan.');}
 function refresh(){if(locked)return;if(dirty&&!window.confirm('Perbarui data dari server? Unduh salinan perubahan terlebih dahulu.'))return;setWaiting(true);router.refresh();}
 function backup(){try{const url=URL.createObjectURL(new Blob([cmsBackup(document)],{type:'application/json'}));const a=window.document.createElement('a');a.href=url;a.download='kastriva-cms-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Salinan belum dapat dibuat.');}}
 async function importFile(file:File|undefined){if(!file||locked)return;try{if(file.size>128*1024)throw new Error('Salinan maksimal 128 KB.');load(readCmsBackup(await file.text()),'Salinan JSON');}catch(e){setError(e instanceof Error?e.message:'Salinan tidak valid.');}}
 async function save(){setError('');try{await m.submit({action:'save',revision:initial.revision,request_id:crypto.randomUUID(),catalog_hash:initial.catalog_hash,document:parseCmsDocument(document)});}catch(e){setError(e instanceof Error?e.message:'Periksa formulir.');}}
 async function publish(){if(dirty||!checked||locked)return;if(!window.confirm('Terbitkan draft CMS tersimpan? Konten dan harga katalog untuk pesanan BARU akan diperbarui. Tagihan lama tidak berubah.'))return;await m.submit({action:'publish',revision:initial.revision,request_id:crypto.randomUUID(),catalog_hash:initial.catalog_hash,document:null});}
 function pairs(key:'features'|'steps'){return <>{document.content[key].map((item,i)=><div className="cms-item" key={i}><h3>{key==='steps'?'Langkah':'Keunggulan'} {i+1}</h3><label>Judul<input value={item.title} maxLength={90} onChange={e=>edit({...document,content:{...document.content,[key]:document.content[key].map((v,n)=>n===i?{...v,title:e.target.value}:v)}})}/></label><label>Penjelasan<textarea value={item.body} maxLength={500} rows={3} onChange={e=>edit({...document,content:{...document.content,[key]:document.content[key].map((v,n)=>n===i?{...v,body:e.target.value}:v)}})}/></label>{key==='features'&&<button type="button" className="text-button" disabled={document.content.features.length===1} onClick={()=>edit({...document,content:{...document.content,features:document.content.features.filter((_,n)=>n!==i)}})}>Hapus keunggulan ini</button>}</div>)}{key==='features'&&<button className="button ghost small" disabled={document.content.features.length>=6} onClick={()=>edit({...document,content:{...document.content,features:[...document.content.features,{title:'Keunggulan baru',body:'Jelaskan manfaat yang benar-benar tersedia.'}]}})}>Tambah keunggulan</button>}</>;}
 const catalog=document.catalog.map(row=>({...templates.find(t=>t.slug===row.slug)!,...row}));
 return <div className="cms-studio"><div className="workspace-heading"><div><span className="eyebrow">CMS · TAHAP 6</span><h1>Website di tangan Anda.</h1><p>Draft v{initial.revision} · Published v{initial.published_revision} · {dirty?'Ada edit belum disimpan':'Formulir sama dengan draft server'}</p></div><Link className="button ghost small" href="/" target="_blank" rel="noopener noreferrer">Lihat website ↗</Link></div>
 <div className="cms-toolbar"><div className="button-row"><button className="button ghost small" disabled={locked} onClick={()=>load(initial.live,'Published terkini')}>Muat Published</button><button className="button ghost small" disabled={locked} onClick={()=>load(initial.draft,'Draft server')}>Muat draft server</button><button className="button ghost small" disabled={locked} onClick={refresh}>Perbarui data server</button><button className="button ghost small" onClick={backup}>Unduh salinan</button><button className="button ghost small" disabled={locked} onClick={()=>importRef.current?.click()}>Muat salinan</button><input type="file" ref={importRef} hidden accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];e.target.value='';void importFile(f);}}/></div><div className="button-row"><button className="button ghost small" onClick={()=>setPreview(!preview)}>{preview?'Kembali ke editor':'Preview isian'}</button><button className="button small" disabled={locked||!dirty} onClick={()=>void save()}>{m.busy?'Memproses…':'Simpan draft'}</button></div></div>
 <div className="notice">Muat Published memakai data saat halaman terakhir dimuat. Perbarui data server untuk membaca kondisi terbaru. Simpan draft tidak mengubah halaman publik. Preview isian belum merupakan bukti penyimpanan. Publish memperbarui teks dan katalog dalam satu transaksi database.</div>
 {(error||m.message)&&<div className={'notice '+(m.success&&!error?'':'error')} role="status">{error||m.message}{m.body&&!m.busy&&<button className="button ghost small" disabled={m.blocked} onClick={()=>void m.retry()}>Coba ulang permintaan yang sama</button>}</div>}
 {waiting&&<p className="notice" role="status">Server mengonfirmasi; memuat kondisi terbaru. <button className="text-button" onClick={()=>router.refresh()}>Muat ulang tampilan</button></p>}
 {preview?<div className="cms-preview-full"><div className="cms-preview-label">PREVIEW ISIAN · belum diterbitkan · brand: {document.content.brandName} / {document.content.tagline}</div><MarketingHome content={document.content} catalog={catalog} source="preview"/><div className="cms-preview-footer"><strong>{document.content.brandName}</strong><p>{document.content.footerText}</p><p>{document.content.companyUrl} · {document.content.contactEmail} · {document.content.whatsapp}</p></div></div>:<div className="cms-grid"><nav className="cms-sidebar" aria-label="Bagian CMS">{sections.map(([key,label])=><button className={section===key?'active':''} key={key} aria-current={section===key?'page':undefined} onClick={()=>setSection(key)}>{label}</button>)}</nav><section className="panel cms-fields"><fieldset disabled={locked}>
 {section==='hero'&&<><h2>Kesan pertama.</h2>{text('heroEyebrow','Label di atas judul')}{text('heroTitle','Judul utama',true)}{text('heroAccent','Judul aksen')}{text('heroBody','Deskripsi hero',true)}<div className="form-grid">{text('heroPrimary','Tombol katalog')}{text('heroSecondary','Tombol demo')}</div><p className="muted">Tujuan tombol tetap katalog dan demo. Jalur aplikasi tidak dapat diganti dengan script atau URL bebas.</p></>}
 {section==='tentang'&&<><h2>Tentang & keunggulan.</h2>{text('aboutTitle','Judul tentang')}{text('aboutBody','Tentang layanan',true)}{text('featuresTitle','Judul keunggulan')}{pairs('features')}</>}
 {section==='alur'&&<><h2>Koleksi & cara kerja.</h2>{text('collectionTitle','Judul koleksi')}{text('collectionBody','Penjelasan koleksi',true)}{text('stepsTitle','Judul cara kerja')}{pairs('steps')}</>}
 {section==='faq'&&<><h2>Pertanyaan pelanggan.</h2>{text('faqTitle','Judul FAQ')}{document.content.faqs.map((f,i)=><div className="cms-item" key={i}><label>Pertanyaan {i+1}<input value={f.question} maxLength={160} onChange={e=>edit({...document,content:{...document.content,faqs:document.content.faqs.map((v,n)=>n===i?{...v,question:e.target.value}:v)}})}/></label><label>Jawaban<textarea rows={4} maxLength={800} value={f.answer} onChange={e=>edit({...document,content:{...document.content,faqs:document.content.faqs.map((v,n)=>n===i?{...v,answer:e.target.value}:v)}})}/></label><button className="text-button" disabled={document.content.faqs.length===1} onClick={()=>edit({...document,content:{...document.content,faqs:document.content.faqs.filter((_,n)=>n!==i)}})}>Hapus pertanyaan</button></div>)}<button className="button ghost small" disabled={document.content.faqs.length>=8} onClick={()=>edit({...document,content:{...document.content,faqs:[...document.content.faqs,{question:'Pertanyaan baru?',answer:'Jawaban yang sesuai dengan layanan saat ini.'}]}})}>Tambah pertanyaan</button></>}
 {section==='cta'&&<><h2>Ajakan di akhir halaman.</h2>{text('ctaTitle','Judul ajakan')}{text('ctaBody','Deskripsi',true)}{text('ctaLabel','Label tombol katalog')}</>}
 {section==='kontak'&&<><h2>Brand, footer & kontak.</h2><div className="form-grid">{text('brandName','Nama brand')}{text('tagline','Subjudul brand')}</div>{text('footerText','Kalimat footer',true)}{text('contactEmail','Email kontak publik (opsional)')}{text('whatsapp','WhatsApp publik, format 628… (opsional)')}{text('companyUrl','Website utama (origin HTTPS)')}<p className="notice">Kontak ini tampil publik. Rekening pembayaran tetap di Pengaturan transaksi. Copyright Kastriva dan halaman privasi tidak diubah melalui CMS ini.</p></>}
 {section==='seo'&&<><h2>Informasi mesin pencari.</h2>{text('seoTitle','Judul beranda, 10–70 karakter')}{text('seoDescription','Deskripsi, 20–180 karakter',true)}<label className="checkbox"><input type="checkbox" checked={document.content.allowIndex} onChange={e=>edit({...document,content:{...document.content,allowIndex:e.target.checked}})}/><span>Izinkan indeks beranda, katalog, dan harga setelah layanan siap.</span></label><p className="notice">Default nonaktif untuk pengujian. Admin, akun, demo, dan undangan tamu tetap noindex. Pilihan ini bukan jaminan peringkat Google atau perlindungan akses.</p></>}
 {section==='katalog'&&<><h2>Tema & harga.</h2><p>{document.catalog.length} desain tersedia. Atur nama, deskripsi, harga, urutan, dan ketersediaan setiap tema.</p>{document.catalog.map((t,i)=><div className="cms-item" key={t.slug}><div className="cms-item-heading"><code>{t.slug}</code><div className="button-row">{[-1,1].map(delta=><button aria-label={(delta<0?'Naikkan ':'Turunkan ')+t.name} className="button ghost small" key={delta} disabled={i+delta<0||i+delta>=document.catalog.length} onClick={()=>{const rows=[...document.catalog];[rows[i],rows[i+delta]]=[rows[i+delta],rows[i]];edit({...document,catalog:rows});}}>{delta<0?'↑':'↓'}</button>)}</div></div><label>Nama tema<input value={t.name} maxLength={80} onChange={e=>edit({...document,catalog:document.catalog.map((v,n)=>n===i?{...v,name:e.target.value}:v)})}/></label><label>Deskripsi<textarea rows={3} maxLength={500} value={t.description} onChange={e=>edit({...document,catalog:document.catalog.map((v,n)=>n===i?{...v,description:e.target.value}:v)})}/></label><label>Harga rupiah<input type="number" min={1000} max={100000000} step={1} value={t.price} onChange={e=>edit({...document,catalog:document.catalog.map((v,n)=>n===i?{...v,price:Number(e.target.value)}:v)})}/></label><label className="checkbox"><input type="checkbox" checked={t.active} onChange={e=>edit({...document,catalog:document.catalog.map((v,n)=>n===i?{...v,active:e.target.checked}:v)})}/><span>Tampilkan di katalog / tersedia untuk pilihan baru</span></label></div>)}<p className="notice">Menonaktifkan tema tidak menarik undangan terbit dan tidak menghapus draft lama. Checkout baru tema tersebut ditutup. Pernikahan, ulang tahun, aqiqah, dan acara kantor dapat dipesan melalui alur yang sama.</p></>}
 {section==='riwayat'&&<><h2>20 publikasi terakhir.</h2><p>Memuat versi lama hanya mengisi formulir. Periksa ulang harga/kontak, simpan draft, lalu publish bila memang diperlukan.</p>{initial.history.map(h=><article className="cms-item" key={h.revision}><strong>Published v{h.revision}</strong><p>{new Date(h.published_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p><button className="button ghost small" onClick={()=>load(h.document,'Published v'+h.revision)}>Muat sebagai draft</button></article>)}</>}
 </fieldset></section></div>}
 <section className="panel cms-publish"><div><span className="eyebrow">LANGKAH TERAKHIR</span><h2>Terbitkan dengan yakin.</h2><p>{dirty?'Simpan perubahan terlebih dahulu.':'Publish menggunakan draft server v'+initial.revision+'.'} Harga baru hanya berlaku pada pesanan yang dibuat sesudahnya.</p><label className="checkbox"><input type="checkbox" checked={checked} disabled={locked||dirty} onChange={e=>setChecked(e.target.checked)}/><span>Saya sudah memeriksa teks, kontak, harga, dan preview draft yang tersimpan.</span></label></div><div className="button-row"><Link className="button ghost" href="/admin/cms/preview" target="_blank" rel="noopener noreferrer">Preview draft server ↗</Link><button className="button" disabled={locked||dirty||!checked} onClick={()=>void publish()}>Publish website</button></div></section>
 </div>;
}
