import Link from 'next/link';
import ThemeCard,{ThemeArtwork} from '@/components/ThemeCard';
import {getTemplate} from '@/lib/templates';
import type {CmsContent} from '@/lib/cms';
import type {Template} from '@/lib/types';
export default function MarketingHome({content:c,catalog,source='database'}:{content:CmsContent;catalog:Template[];source?:'database'|'demo'|'unavailable'|'preview'}){
 const active=catalog.filter(t=>t.active);
 const featured=['pernikahan','ulang-tahun','aqiqah','acara-kantor'].flatMap(category=>active.filter(t=>t.category===category).slice(0,1));
 const wedding=catalog.filter(t=>t.active&&t.category==='pernikahan');const hero=wedding[0]||getTemplate('elegant-rose')!,back=wedding[1]||getTemplate('rustic-wood')!;
 const Element=source==='preview'?'div':'main';
 return <Element className="cms-marketing">{source==='unavailable'&&<div className="container notice error" role="status">Konten terbaru dan katalog belum dapat dimuat. Harga tidak ditampilkan sampai koneksi pulih.</div>}{source==='demo'&&<div className="container notice">Mode demo lokal: backend belum terhubung. Harga adalah referensi, bukan penawaran aktif.</div>}
 <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow pill"><span className="live-dot"/>{c.heroEyebrow}</span><h1 className="cms-linebreak">{c.heroTitle}<br/><em>{c.heroAccent}</em></h1><p>{c.heroBody}</p><div className="button-row"><Link className="button" href="/tema">{c.heroPrimary} ↗</Link>{wedding[0]&&<Link className="button ghost" href={'/demo/'+wedding[0].slug}>▷ {c.heroSecondary}</Link>}</div><div className="hero-facts"><span><strong>{active.length} tema</strong>untuk beragam acara</span><span><strong>Tanpa login</strong>untuk melihat demo</span><span><strong>Responsif</strong>di HP & desktop</span></div></div><div className="hero-visual"><div className="visual-caption"><span>DESIGNED WITH LOVE</span><i>your story, beautifully told.</i></div><div className="hero-back-card"><ThemeArtwork template={back}/></div><div className="hero-front-card"><ThemeArtwork template={hero} large/></div><div className="floating-note"><span aria-hidden>♡</span><div>Bukan sekadar undangan.<small>Awal dari cerita indah Anda.</small></div></div></div></div></section>
 <section className="container section cms-about"><span className="eyebrow">TENTANG KAMI</span><h2>{c.aboutTitle}</h2><p>{c.aboutBody}</p></section>
 <section className="section section-tint"><div className="container"><div className="section-heading"><h2>{c.featuresTitle}</h2></div><div className="steps-grid">{c.features.map((f,i)=><article key={i}><span aria-hidden>✦</span><h3>{f.title}</h3><p>{f.body}</p></article>)}</div></div></section>
 <section className="section container"><div className="section-heading"><div><span className="eyebrow">KOLEKSI PILIHAN</span><h2>{c.collectionTitle}</h2></div><div><p>{c.collectionBody}</p><Link className="text-link" href="/tema">Jelajahi semua tema ↗</Link></div></div><div className="theme-grid">{featured.map(t=><ThemeCard key={t.slug} template={t} priceLabel={source==='demo'?'Harga referensi tema':'Harga katalog saat ini'}/>)}</div>{!active.length&&<p className="notice">Belum ada tema yang tersedia untuk dipilih.</p>}</section>
 <section className="section section-tint"><div className="container"><span className="eyebrow">SEDERHANA DARI AWAL</span><div className="section-heading"><h2>{c.stepsTitle}</h2></div><div className="steps-grid">{c.steps.map((f,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{f.title}</h3><p>{f.body}</p></article>)}</div></div></section>
 <section className="section container faq-section"><div><span className="eyebrow">SEBELUM MEMULAI</span><h2>{c.faqTitle}</h2></div><div>{c.faqs.map((f,i)=><details key={i}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div></section>
 <section className="container"><div className="cta-panel"><div><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>{c.ctaTitle}</h2><p>{c.ctaBody}</p></div><Link className="button light" href="/tema">{c.ctaLabel} ↗</Link></div><p className="stage-note">Coba demo tanpa akun. Draft Anda tetap privat sampai Anda memilih untuk menerbitkannya setelah pembayaran terverifikasi.</p></section>
 </Element>;
}
