 'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {parseCheckout,type CommerceSettings} from '@/lib/commerce';
import {currency} from '@/lib/domain';
import {useCommerceMutation} from './useCommerceMutation';
import MutationFeedback from './MutationFeedback';
export default function CheckoutForm({owner,id,revision,theme,name,price,settings,enabled}:{owner:string;id:string;revision:number;theme:string;name:string;price:number;settings:CommerceSettings;enabled:boolean}){
 const router=useRouter(),[error,setError]=useState('');const m=useCommerceMutation(owner,'checkout:'+id,'/api/commerce/checkout',result=>router.push('/dashboard/pesanan/'+result.id));
 return <form className="panel commerce-form" onSubmit={e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{const body=parseCheckout({invitation_id:id,draft_revision:revision,theme,quoted_price:price,quoted_days:settings.active_days,settings_revision:settings.revision,customer_name:f.get('name'),customer_phone:f.get('phone'),request_id:crypto.randomUUID()});void m.submit(body);}catch(ex){setError(ex instanceof Error?ex.message:'Periksa formulir.');}}}><span className="eyebrow">01 · KONFIRMASI PESANAN</span><h2>Mulai dari cerita Anda.</h2><p>Pesanan dibuat dari draft versi {revision}. Belum ada pemotongan dana otomatis.</p><fieldset disabled={m.locked||!enabled}><label>Nama pemesan<input name="name" minLength={2} maxLength={100} required autoComplete="name" defaultValue={name}/></label><label>WhatsApp<input name="phone" type="tel" required pattern="62[0-9]{8,13}" placeholder="6281234567890" autoComplete="tel" maxLength={15}/><small>Gunakan 62, tanpa tanda + atau spasi.</small></label><label className="checkbox"><input name="terms" type="checkbox" required/><span>Saya telah memeriksa tema, biaya {currency(price)}, dan masa aktif {settings.active_days} hari sejak verifikasi pembayaran. Harga/rekening dikunci untuk pesanan ini.</span></label><label className="checkbox"><input type="checkbox" required/><span>Saya memahami undangan belum terbit dan pembayaran diperiksa manual oleh admin. Ketentuan pembatalan/refund dikonfirmasi kepada Kastriva; tidak diproses otomatis.</span></label><button className="button full" type="submit">{m.busy?'Membuat pesanan…':'Buat pesanan · '+currency(price)}</button></fieldset>{!enabled&&<p className="notice">Checkout belum dibuka oleh pengelola. Draft tetap dapat diedit.</p>}{error&&<p className="notice error" role="alert">{error}</p>}<MutationFeedback state={m}/></form>;
}
