import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireUser,requireAdmin} from '@/lib/server-auth';
import {UUID,currency,parseDraft} from '@/lib/domain';
import {SALE_LABEL,readyToPublish,saleTimestamp,type Sale,type Publication,type SaleEvent} from '@/lib/commerce';
import {publishingAppEnabled,privateStorageKey} from '@/lib/commerce-server';
import {siteUrl} from '@/lib/config';
import PaymentActions from './PaymentActions';
import PublicationControls from './PublicationControls';
import PrintOrder from './PrintOrder';
import RefreshButton from '@/components/RefreshButton';
export default async function OrderDetailPage({id,admin=false}:{id:string;admin?:boolean}){
 if(!UUID.test(id))notFound();const {db,user}=admin?await requireAdmin():await requireUser('/dashboard/pesanan/'+id);
 let saleQuery=db.from('ki_sales').select('*').eq('id',id);if(!admin)saleQuery=saleQuery.eq('owner_id',user.id);const{data:s,error:se}=await saleQuery.maybeSingle();if(se)throw new Error('SALE_LOAD_FAILED');if(!s)notFound();const sale=s as Sale;
 const[{data:p,error:pe},{data:ev,error:ee},{data:cfg,error:ce}]=await Promise.all([db.from('ki_publications').select('*').eq('sale_id',id).maybeSingle(),db.from('ki_sale_events').select('id,sale_id,action,old_status,new_status,note,created_at').eq('sale_id',id).order('id',{ascending:false}).limit(50),db.from('ki_commerce_settings').select('publishing_enabled').eq('id',1).single()]);if(pe||ee||ce)throw new Error('SALE_DETAILS_UNAVAILABLE');const publication=p as Publication|null;
 let draftRevision=1;const errors:string[]=[];
 if(!admin){const{data:d,error:de}=await db.from('ki_invitations').select('revision,theme_slug,content').eq('id',sale.invitation_id).eq('owner_id',user.id).maybeSingle();if(de||!d)throw new Error('DRAFT_UNAVAILABLE');draftRevision=d.revision;errors.push(...readyToPublish(parseDraft(d.content,user.id)));if(d.theme_slug!==sale.theme_slug)errors.push('Kembalikan tema draft ke '+sale.theme_name+' sesuai pesanan sebelum menerbitkan.');if(d.content.photoPaths.length&&!privateStorageKey())errors.push('Proxy foto publik belum diaktifkan pengelola. Foto tetap privat.');}
 const labels:Record<string,string>={checkout:'Pesanan dibuat',submit_payment:'Konfirmasi transfer',approve:'Pembayaran disetujui',reject:'Konfirmasi ditolak',cancel:'Pesanan dibatalkan',revoke:'Akses dicabut',publish:'Undangan diterbitkan',unpublish:'Undangan ditarik'};
 return <main className="container workspace order-document"><div className="workspace-heading"><div><Link className="back-link no-print" href={admin?'/admin':'/dashboard/pesanan'}>← Daftar pesanan</Link><span className="eyebrow">KASTRIVA INVITATION</span><h1>Detail pesanan.</h1><p className="order-code">{sale.order_code}</p></div><div className="button-row"><RefreshButton/><PrintOrder/></div></div><div className="commerce-grid"><div className="commerce-stack"><section className="panel commerce-summary"><span className={'badge sale-'+sale.status}>{SALE_LABEL[sale.status]}</span><h2>{sale.theme_name}</h2><strong className="commerce-price">{currency(sale.total_price)}</strong><p>{sale.status==='paid'?'Dana ditandai terverifikasi oleh admin; periksa masa aktif di bawah.':'Ringkasan pesanan ini bukan bukti pembayaran lunas.'}</p><dl className="commerce-facts"><div><dt>Pemesan</dt><dd>{sale.customer_name}<br/>{sale.customer_email}<br/>{sale.customer_phone}</dd></div><div><dt>Dibuat</dt><dd>{saleTimestamp(sale.created_at)}</dd></div><div><dt>Masa aktif paket</dt><dd>{sale.active_days} hari sejak verifikasi</dd></div><div><dt>Disetujui admin</dt><dd>{saleTimestamp(sale.paid_at)}</dd></div><div><dt>Berakhir</dt><dd>{saleTimestamp(sale.expires_at)}</dd></div></dl>{sale.admin_note&&<p className="notice pre-line">Catatan admin: {sale.admin_note}</p>}<small>Dokumen ringkasan layanan, bukan faktur pajak. Pembatalan atau pencabutan akses tidak otomatis mengembalikan dana.</small></section>
 <section className="panel"><span className="eyebrow">REKENING SAAT PESANAN DIBUAT</span><h2>Tujuan transfer</h2><dl className="commerce-facts"><div><dt>Bank</dt><dd>{sale.payment_details.bank_name}</dd></div><div><dt>Rekening</dt><dd className="selectable">{sale.payment_details.bank_account}</dd></div><div><dt>Atas nama</dt><dd>{sale.payment_details.bank_holder}</dd></div><div><dt>Jumlah</dt><dd>{currency(sale.total_price)}</dd></div></dl>{sale.payment_details.instructions&&<p className="pre-line">{sale.payment_details.instructions}</p>}<p className="notice">Pastikan nama penerima cocok. Setelah transfer, kirim konfirmasi satu kali. Jangan transfer lagi hanya karena status belum berubah.</p>{sale.payment_reference&&<p>Referensi dari pelanggan: <strong>{sale.payment_reference}</strong></p>}</section>
 <section className="panel"><span className="eyebrow">JEJAK PERUBAHAN</span><h2>Riwayat pesanan</h2><p>Menampilkan maksimal 50 perubahan terbaru.</p><div className="commerce-timeline">{(ev as SaleEvent[]).map(event=><article key={event.id}><span className="timeline-dot" aria-hidden/><div><strong>{labels[event.action]||event.action}</strong><small>{saleTimestamp(event.created_at)}</small>{event.note&&<p className="pre-line">{event.note}</p>}</div></article>)}</div></section></div>
 <aside className="commerce-stack">{!admin&&<div className="panel no-print"><span className="eyebrow">TAHAP 5</span><h3>Tamu & konfirmasi</h3><p>Siapkan tautan personal, pantau kehadiran, dan moderasi ucapan.</p><Link className="button full" href={`/dashboard/pesanan/${sale.id}/tamu`}>Kelola tamu & RSVP →</Link></div>}<PaymentActions key={sale.id+':'+sale.revision} owner={user.id} sale={sale} admin={admin}/>{!admin&&<PublicationControls key={sale.id+':'+sale.revision+':'+(publication?.revision||0)+':'+draftRevision} owner={user.id} sale={sale} publication={publication} draftRevision={draftRevision} errors={errors} enabled={publishingAppEnabled()&&cfg.publishing_enabled===true} origin={siteUrl()}/>}{admin&&<div className="panel no-print"><h3>Publikasi pelanggan</h3><p>{publication?`Alamat: /u/${publication.slug} · versi draft ${publication.draft_revision}`:'Pelanggan belum menerbitkan undangan.'}</p><p>Admin memverifikasi dana. Penerbitan dilakukan pemilik akun setelah menyetujui data yang ditampilkan.</p><Link className="button ghost small" href="/admin/transaksi">Pengaturan transaksi</Link></div>}</aside></div></main>;
}
