 'use client';
import {useState} from 'react';
import type {Sale,SaleAction} from '@/lib/commerce';
import {canAct,parseSaleAction} from '@/lib/commerce';
import {currency} from '@/lib/domain';
import {useCommerceMutation} from './useCommerceMutation';
import MutationFeedback from './MutationFeedback';
export default function PaymentActions({sale,owner,admin=false}:{sale:Sale;owner:string;admin?:boolean}){
 const actions:SaleAction[]=admin?(['approve','reject','cancel','revoke'] as SaleAction[]).filter(a=>canAct(sale.status,a,true)):(['submit_payment','cancel'] as SaleAction[]).filter(a=>canAct(sale.status,a,false));
 const[action,setAction]=useState<SaleAction>(actions[0]||'submit_payment'),[error,setError]=useState('');const m=useCommerceMutation(owner,'sale:'+sale.id,'/api/commerce/action');
 const labels:Record<SaleAction,string>={submit_payment:'Saya sudah transfer — ajukan verifikasi',approve:'Setujui pembayaran',reject:'Tolak konfirmasi',cancel:'Batalkan pesanan',revoke:'Cabut akses publik'};
 return <section className="panel commerce-form no-print"><span className="eyebrow">{admin?'PEMERIKSAAN ADMIN':'KONFIRMASI TRANSFER'}</span><h2>{admin?'Periksa, lalu putuskan.':'Pembayaran Anda.'}</h2>{!actions.length?<p>Tidak ada tindakan pembayaran untuk status ini. Gunakan tombol muat ulang untuk memeriksa pembaruan.</p>:<form onSubmit={e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{if(['cancel','revoke'].includes(action)&&!window.confirm(action==='revoke'?'Cabut akses? Undangan berhenti ditampilkan. Ini bukan refund dan tidak mengembalikan dana.':'Batalkan pesanan? Tidak ada pengembalian dana otomatis. Pesanan tidak dapat dibuka ulang pada tahap ini.'))return;
 const body=parseSaleAction({sale_id:sale.id,action,revision:sale.revision,request_id:crypto.randomUUID(),note:String(f.get('note')||''),reference:String(f.get('reference')||''),received_amount:action==='approve'?Number(f.get('amount')):0,verified:action==='approve'&&f.get('verified')==='on'},admin);void m.submit(body);}catch(ex){setError(ex instanceof Error?ex.message:'Periksa formulir.');}}}><fieldset disabled={m.locked}><label>Tindakan<select value={action} onChange={e=>setAction(e.target.value as SaleAction)}>{actions.map(a=><option value={a} key={a}>{labels[a]}</option>)}</select></label>{(action==='submit_payment'||action==='approve')&&<label>{action==='approve'?'Referensi mutasi yang sudah dicocokkan':'Nama pengirim, referensi transfer, tanggal / jam'}<input name="reference" required minLength={3} maxLength={160} placeholder={admin?'Referensi pada rekening penerima':'Contoh: Andi · TRX123 · 24/09 10.30 WIB'}/></label>}{action==='approve'&&<><label>Dana yang benar-benar diterima (rupiah)<input name="amount" inputMode="numeric" type="number" min={1} max={2147483647} step={1} required placeholder="Tanpa titik atau koma"/></label><p className="notice">Tagihan {currency(sale.total_price)}. Cocokkan mutasi rekening, bukan hanya ucapan pelanggan atau gambar bukti transfer.</p><label className="checkbox"><input type="checkbox" name="verified" required/><span>Saya sudah memeriksa rekening penerima dan memastikan dana masuk sesuai tagihan. Persetujuan memulai masa aktif {sale.active_days} hari, bukan menerbitkan undangan otomatis.</span></label></>}<label>Catatan {['reject','revoke'].includes(action)?'(wajib)':'(opsional)'}<textarea name="note" rows={3} maxLength={500} minLength={['reject','revoke'].includes(action)?5:0} required={['reject','revoke'].includes(action)}/><small>Catatan dapat dibaca pelanggan. Jangan tulis saldo, password, atau data rekening orang lain.</small></label>{action==='submit_payment'&&<p className="notice">Tombol ini hanya mengajukan pemeriksaan. Status belum menjadi lunas dan undangan belum terbit.</p>}{action==='revoke'&&<p className="notice error">Pencabutan akses tidak mengembalikan uang dan tidak dapat dibuka ulang melalui halaman ini.</p>}<button className="button full" type="submit">{m.busy?'Memproses…':labels[action]}</button></fieldset></form>}{error&&<p className="notice error" role="alert">{error}</p>}<MutationFeedback state={m}/></section>;
}
