 'use client';
import {useState} from 'react';
import Link from 'next/link';
import {parsePublication,type Sale,type Publication,publicationAvailable,shareUrl} from '@/lib/commerce';
import {useCommerceMutation} from './useCommerceMutation';
import MutationFeedback from './MutationFeedback';
export default function PublicationControls({owner,sale,publication,draftRevision,errors,enabled,origin}:{owner:string;sale:Sale;publication:Publication|null;draftRevision:number;errors:string[];enabled:boolean;origin:string}){
 const[slug,setSlug]=useState(publication?.slug||'undangan-'+sale.id.replace(/-/g,'').slice(0,12)),[consent,setConsent]=useState(false),[guest,setGuest]=useState(''),[copied,setCopied]=useState(''),[error,setError]=useState('');
 const m=useCommerceMutation(owner,'publication:'+sale.id,'/api/commerce/publication');const active=publicationAvailable(sale,publication,enabled,Date.now());const url=publication?shareUrl(origin,publication.slug,guest):'';
 const expired=!sale.expires_at||Date.parse(sale.expires_at)<=Date.now(),canPublish=enabled&&sale.status==='paid'&&!expired&&!errors.length;
 async function act(action:'publish'|'unpublish'){setError('');try{const body=parsePublication({sale_id:sale.id,action,slug,draft_revision:draftRevision,publication_revision:publication?.revision||0,request_id:crypto.randomUUID(),consent:action==='publish'?consent:false});if(action==='unpublish'&&!window.confirm('Tarik undangan dari publik? Masa aktif tetap berjalan.'))return;await m.submit(body);}catch(ex){setError(ex instanceof Error?ex.message:'Periksa isian.');}}
 return <section className="panel commerce-form no-print"><span className="eyebrow">PUBLIKASI TERKENDALI</span><h2>Siap dibagikan?</h2><p>Draft terbaru: versi {draftRevision}. {publication?`Versi yang diterbitkan: ${publication.draft_revision}.`:'Belum ada versi publik.'} Mengedit draft tidak mengubah halaman tamu sampai Anda menerbitkan pembaruan.</p><div className="button-row"><Link className="button ghost small" href={'/dashboard/undangan/'+sale.invitation_id}>Edit draft</Link><Link className="button ghost small" target="_blank" rel="noopener noreferrer" href={'/dashboard/undangan/'+sale.invitation_id+'/preview'}>Periksa preview ↗</Link></div>
 {errors.length>0&&<div className="notice error">{errors.map(x=><p key={x}>{x}</p>)}</div>}
 <fieldset disabled={m.locked}><label>Alamat undangan<input value={slug} readOnly={!!publication} maxLength={64} minLength={5} onChange={e=>setSlug(e.target.value)} spellCheck={false} autoCapitalize="none"/><small>/u/{slug} · Setelah publikasi pertama, alamat ini tetap dan tidak dapat diubah.</small></label><label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={!canPublish}/><span>Saya menyetujui nama, keluarga, jadwal, lokasi, cerita, dan foto pada versi ini ditampilkan kepada siapa pun yang mempunyai tautan. Konten yang sudah disalin tamu tidak dapat ditarik kembali.</span></label><div className="button-row"><button type="button" className="button" disabled={!canPublish||!consent} onClick={()=>void act('publish')}>{publication?'Terbitkan versi terbaru':'Terbitkan undangan'}</button>{publication?.active&&<button type="button" className="button ghost" onClick={()=>void act('unpublish')}>Tarik dari publik</button>}</div></fieldset>
 {!canPublish&&<p className="notice">{sale.status!=='paid'?'Menunggu pembayaran terverifikasi.':expired?'Masa aktif berakhir. Hubungi pengelola.':!enabled?'Pengelola belum membuka publikasi.':'Perbaiki draft sebelum menerbitkan.'}</p>}
 {active&&<div className="share-box"><span className="badge">TERBIT</span><label>Nama tamu (opsional, hanya sapaan)<input value={guest} maxLength={100} onChange={e=>{setGuest(e.target.value);setCopied('');}}/></label><label>Tautan untuk dibagikan<input id={'share-'+sale.id} value={url} readOnly onFocus={e=>e.currentTarget.select()}/></label><div className="button-row"><button type="button" className="button ghost small" onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied('Tautan disalin.');}catch{const input=document.getElementById('share-'+sale.id) as HTMLInputElement|null;input?.focus();input?.select();setCopied('Tautan dipilih. Tekan lama lalu Salin, atau Ctrl+C.');}}}>Salin tautan</button><a className="button small" href={'https://wa.me/?text='+encodeURIComponent('Dengan hormat, kami mengundang '+(guest.trim()||'Bapak/Ibu/Saudara/i')+' untuk hadir dalam acara kami. Detail undangan: '+url)} target="_blank" rel="noopener noreferrer">Bagikan WhatsApp ↗</a><a className="text-button" href={url} target="_blank" rel="noopener noreferrer">Buka undangan ↗</a></div>{copied&&<p role="status">{copied}</p>}<small>Ini tautan undangan umum. Nama pada URL hanya sapaan; tautan ini belum memberikan akses RSVP. Gunakan menu Tamu & RSVP untuk membuat dan membagikan tautan khusus tiap tamu.</small></div>}
 {error&&<p className="notice error" role="alert">{error}</p>}<MutationFeedback state={m}/></section>;
}
