 'use client';
import {useState} from 'react';
import Link from 'next/link';
import {parsePublication,type Sale,type Publication,publicationAvailable} from '@/lib/commerce';
import {useCommerceMutation} from './useCommerceMutation';
import MutationFeedback from './MutationFeedback';
import InvitationShare from './InvitationShare';
export default function PublicationControls({owner,sale,publication,draftRevision,errors,enabled,origin}:{owner:string;sale:Sale;publication:Publication|null;draftRevision:number;errors:string[];enabled:boolean;origin:string}){
 const[slug,setSlug]=useState(publication?.slug||'undangan-'+sale.id.replace(/-/g,'').slice(0,12)),[consent,setConsent]=useState(false),[error,setError]=useState('');
 const m=useCommerceMutation(owner,'publication:'+sale.id,'/api/commerce/publication');const active=publicationAvailable(sale,publication,enabled,Date.now());
 const expired=!sale.expires_at||Date.parse(sale.expires_at)<=Date.now(),canPublish=enabled&&sale.status==='paid'&&!expired&&!errors.length;
 async function act(action:'publish'|'unpublish'){setError('');try{const body=parsePublication({sale_id:sale.id,action,slug,draft_revision:draftRevision,publication_revision:publication?.revision||0,request_id:crypto.randomUUID(),consent:action==='publish'?consent:false});if(action==='unpublish'&&!window.confirm('Tarik undangan dari publik? Masa aktif tetap berjalan.'))return;await m.submit(body);}catch(ex){setError(ex instanceof Error?ex.message:'Periksa isian.');}}
 return <section id="publikasi" className="panel commerce-form no-print"><span className="eyebrow">SEBELUM DIBAGIKAN</span><h2>Siap dibagikan?</h2><p>Draft terbaru: versi {draftRevision}. {publication?`Versi yang diterbitkan: ${publication.draft_revision}.`:'Belum ada versi publik.'} Mengedit draft tidak mengubah halaman tamu sampai Anda menerbitkan pembaruan.</p><div className="button-row"><Link className="button ghost small" href={'/dashboard/undangan/'+sale.invitation_id}>Edit draft</Link><Link className="button ghost small" target="_blank" rel="noopener noreferrer" href={'/dashboard/undangan/'+sale.invitation_id+'/preview'}>Periksa preview ↗</Link></div>
 <div className="publication-checklist"><h3>Checklist sebelum terbit</h3><ul><li>{errors.length?'Lengkapi bagian berikut:':'✓ Isian wajib lengkap dan tema sesuai pesanan.'}</li>{errors.map(x=><li key={x}><Link href={'/dashboard/undangan/'+sale.invitation_id+'#'+(x.includes('mempelai')?'pasangan':x.includes('acara')?'acara':x.includes('foto')?'galeri':'review')}>{x} →</Link></li>)}<li>{sale.status==='paid'&&!expired?'✓ Pembayaran terverifikasi dan masa aktif berlaku.':'Pembayaran terverifikasi dan masa aktif berlaku diperlukan.'}</li><li><Link href={'/dashboard/undangan/'+sale.invitation_id+'#galeri'}>Periksa galeri foto (opsional) →</Link></li><li>Periksa preview, lalu setujui penayangan data di bawah.</li></ul></div>
 <fieldset disabled={m.locked}><label>Alamat undangan<input value={slug} readOnly={!!publication} maxLength={64} minLength={5} onChange={e=>setSlug(e.target.value)} spellCheck={false} autoCapitalize="none"/><small>/u/{slug} · Setelah publikasi pertama, alamat ini tetap dan tidak dapat diubah.</small></label><label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={!canPublish}/><span>Saya menyetujui nama, keluarga, jadwal, lokasi, cerita, dan foto pada versi ini ditampilkan kepada siapa pun yang mempunyai tautan. Konten yang sudah disalin tamu tidak dapat ditarik kembali.</span></label><div className="button-row"><button type="button" className="button" disabled={!canPublish||!consent} onClick={()=>void act('publish')}>{publication?'Terbitkan versi terbaru':'Terbitkan undangan'}</button>{publication?.active&&<button type="button" className="button ghost" onClick={()=>void act('unpublish')}>Tarik dari publik</button>}</div></fieldset>
 {!canPublish&&<p className="notice">{sale.status!=='paid'?'Menunggu pembayaran terverifikasi.':expired?'Masa aktif berakhir. Hubungi pengelola.':!enabled?'Pengelola belum membuka publikasi.':'Perbaiki draft sebelum menerbitkan.'}</p>}
 {active&&publication&&<>{draftRevision>publication.draft_revision&&<p className="notice" role="status">Ada perubahan draft yang belum terbit. Tamu masih melihat versi sebelumnya. Periksa preview dan terbitkan versi terbaru sebelum membagikan tautan.</p>}<InvitationShare origin={origin} publication={publication}/></>}
 {error&&<p className="notice error" role="alert">{error}</p>}<MutationFeedback state={m}/></section>;
}
