'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ATTENDANCE,MAX_GUESTS,MAX_BATCH,PAGE_SIZE,parseGuestCommand,parseGuestAck,parseWorkspace,parseGuestLink,decodeGuestPending,personalGuestUrl,guestShareMessage,type GuestCommand,type GuestWorkspace,type GuestRow,type GuestAction} from '@/lib/guests';
import {guestRequest} from '@/lib/guest-transport';
import {useRetainedRequest} from './useRetainedRequest';
type LinkInfo={name:string;url:string;message:string};
export default function GuestManager({owner,initial,origin,appEnabled}:{owner:string;initial:GuestWorkspace;origin:string;appEnabled:boolean}){
 const [addEpoch,setAddEpoch]=useState(0);
 const [book,setBook]=useState(initial),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[link,setLink]=useState<LinkInfo|null>(null),[fallbackText,setFallbackText]=useState(''),[edit,setEdit]=useState<string|null>(null),[linkBusy,setLinkBusy]=useState<string|null>(null),[exporting,setExporting]=useState(false);
 const loadVersion=useRef(0),linkField=useRef<HTMLTextAreaElement>(null),linkHeading=useRef<HTMLHeadingElement>(null),linkFlight=useRef(false);
 useEffect(()=>{if(link)linkHeading.current?.focus();},[link]);
 const load=useCallback(async(offset=0,q=query,f=filter)=>{
  const id=++loadVersion.current;setLoading(true);setError('');
  try{const next=await guestRequest('/api/guestbook/workspace',{sale_id:initial.sale_id,query:q,filter:f,offset},parseWorkspace);if(id===loadVersion.current)setBook(next);}
  catch(e){if(id===loadVersion.current)setError(e instanceof Error?e.message:'Daftar tamu belum dimuat.');}
  finally{if(id===loadVersion.current)setLoading(false);}
 },[initial.sale_id,query,filter]);
 useEffect(()=>()=>{++loadVersion.current;},[]);
 const mutation=useRetainedRequest({storageKey:'ki:guests:v1:'+owner+':'+initial.sale_id,
  decode:(raw:string)=>decodeGuestPending(raw,owner,initial.sale_id),encode:(body:GuestCommand)=>JSON.stringify({version:1,owner,body}),
  send:(body:GuestCommand)=>guestRequest('/api/guestbook/manage',body,v=>parseGuestAck(v,body)),
  onSuccess:result=>{if(result.action==='add_many')setAddEpoch(n=>n+1);setEdit(null);setLink(null);void load(0);}});
 async function act(action:GuestAction,guest_id:string|null,revision:number,data:Record<string,unknown>){setError('');setNotice('');
  try{const body=parseGuestCommand({sale_id:initial.sale_id,action,guest_id,revision,request_id:crypto.randomUUID(),data});await mutation.submit(body);}
  catch(e){setError(e instanceof Error?e.message:'Periksa isian.');}
 }
 async function reveal(g:GuestRow){if(linkFlight.current)return;linkFlight.current=true;setLinkBusy(g.id);setError('');setLink(null);
  try{const v=await guestRequest('/api/guestbook/link',{sale_id:book.sale_id,guest_id:g.id},x=>parseGuestLink(x,g.id));const url=personalGuestUrl(origin,v.slug,v.name,v.token);setFallbackText(url);setLink({name:v.name,url,message:guestShareMessage(v.name,url)});}
  catch(e){setError(e instanceof Error?e.message:'Tautan belum dapat dibuat.');}finally{linkFlight.current=false;setLinkBusy(null);}
 }
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Tersalin. Bagikan hanya kepada tamu yang sesuai.');}catch{setFallbackText(value);requestAnimationFrame(()=>{linkField.current?.focus();linkField.current?.select();});setNotice('Salin otomatis tidak tersedia. Teks dipilih; gunakan menu Salin di perangkat.');}}
 async function exportCsv(){if(exporting)return;setExporting(true);setError('');
  try{const res=await fetch('/api/guestbook/export',{method:'POST',credentials:'same-origin',cache:'no-store',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify({sale_id:book.sale_id}),signal:AbortSignal.timeout(20000)});
   if(!res.ok||!res.headers.get('content-type')?.startsWith('text/csv'))throw new Error('Ekspor belum berhasil. Periksa sesi login dan koneksi.');
   const blob=await res.blob();if(blob.size>1024*1024)throw new Error('Ekspor terlalu besar.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='tamu-'+(book.slug||'kastriva')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('CSV seluruh daftar dibuat, tanpa token tautan. Simpan privat; filter layar tidak membatasi ekspor.');
  }catch(e){setError(e instanceof Error?e.message:'Ekspor gagal.');}finally{setExporting(false);}
 }
 const locked=mutation.locked||loading;
 return <main className="container workspace guest-workspace">
  <div className="workspace-heading"><div><span className="eyebrow">SATU UNDANGAN, BANYAK CERITA</span><h1>Tamu & ucapan.</h1><p>Kelola undangan personal dan rangkum konfirmasi kehadiran.</p></div><div className="button-row"><Link className="button ghost small" href={`/dashboard/pesanan/${book.sale_id}`}>← Detail pesanan</Link><button className="button small" disabled={exporting||loading} onClick={exportCsv}>{exporting?'Mengekspor…':'Unduh CSV'}</button></div></div>
  {(!appEnabled||!book.platform_enabled)&&<div className="notice">Penerimaan RSVP belum dibuka pada {appEnabled?'database platform':'deployment ini'}. Daftar tamu tetap dapat disiapkan untuk pesanan aktif. Aktivasi pengelola tersedia di Admin → Tamu & RSVP.</div>}
  {!book.can_manage&&<div className="notice">Pesanan belum terverifikasi atau masa aktif berakhir. Riwayat tetap terbaca; penambahan/aktivasi tamu ditahan. Penonaktifan dan penyembunyian ucapan tetap tersedia.</div>}
  <div className="guest-stats" aria-label="Ringkasan tamu">
   {[['Tamu terdaftar',String(book.stats.registered),`${book.stats.active} tautan aktif`],['Rencana hadir',String(book.stats.people),`${book.stats.yes} tamu/rombongan menjawab Hadir`],['Belum menjawab',String(book.stats.unanswered),'Hanya tamu aktif'],['Perlu moderasi',String(book.stats.pending),'Ucapan menunggu persetujuan']].map(([label,note,detail])=><article className="guest-stat" key={label}><span>{label}</span><strong>{note}</strong><small>{detail}</small></article>)}
  </div><p className="guest-stats-note">Konfirmasi adalah rencana, bukan bukti check-in. Tidak hadir: {book.stats.no} · Belum pasti: {book.stats.maybe}. Kapasitas teknis tahap ini: {MAX_GUESTS} tamu/rombongan per undangan, bukan batas paket komersial baru.</p>
  {(error||mutation.message||notice)&&<div className="guest-feedback" aria-live="polite">{error&&<p className="notice error">{error}</p>}{mutation.message&&<p className={'notice'+(mutation.success?' success':'')}>{mutation.message}</p>}{notice&&<p className="notice">{notice}</p>}{mutation.body&&<button className="button small" disabled={mutation.busy||mutation.blocked} onClick={mutation.retry}>{mutation.busy?'Mengirim…':'Coba ulang permintaan yang sama'}</button>}</div>}
  {link&&<section className="panel guest-link-panel"><h2 ref={linkHeading} tabIndex={-1}>Untuk {link.name}</h2><p>Tautan ini memberi hak mengisi/mengubah RSVP tamu tersebut. Jangan unggah ke status atau grup umum.</p><textarea ref={linkField} aria-label="Tautan personal tamu" readOnly value={fallbackText||link.url} rows={3}/><div className="button-row"><button className="button small" onClick={()=>copy(link.url)}>Salin tautan</button><button className="button ghost small" onClick={()=>copy(link.message)}>Salin pesan</button><a className="button ghost small" href={'https://wa.me/?text='+encodeURIComponent(link.message)} target="_blank" rel="noopener noreferrer">Bagikan via WhatsApp ↗</a><button className="button ghost small" onClick={()=>setLink(null)}>Tutup</button></div><small>WhatsApp dibuka agar Anda memilih penerima. Aplikasi tidak mengirim massal atau menandai pesan sudah diterima.</small></section>}
  <div className="guest-work-grid"><section className="panel guest-list-panel"><div className="guest-section-head"><div><span className="eyebrow">BUKU TAMU PRIVAT</span><h2>Daftar tamu</h2></div><button className="button ghost small" disabled={loading||mutation.busy} onClick={()=>load(book.offset)}>Muat ulang</button></div>
   <form className="guest-filter" onSubmit={e=>{e.preventDefault();void load(0);}}><label>Cari nama<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={100} placeholder="Nama tamu / keluarga"/></label><label>Filter<select value={filter} onChange={e=>setFilter(e.target.value)}>{Object.entries({all:'Semua tamu',unanswered:'Belum menjawab',yes:'Hadir',no:'Tidak hadir',maybe:'Belum pasti',pending:'Ucapan menunggu',approved:'Ucapan disetujui',hidden:'Ucapan disembunyikan',inactive:'Tautan nonaktif'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="button small" disabled={loading}>Terapkan</button></form>
   <div aria-busy={loading}>{!book.rows.length?<div className="empty-state"><h3>{book.stats.registered?'Tidak ada hasil pada filter ini.':'Siapkan tamu pertama Anda.'}</h3><p>{book.stats.registered?'Ubah pencarian atau filter.':'Tambahkan nama, tentukan jumlah orang, lalu bagikan tautan personal setelah undangan terbit.'}</p></div>:book.rows.map(g=><article className={'guest-row'+(!g.active?' is-inactive':'')} key={g.id}>
    <div className="guest-row-head"><div className="guest-avatar" aria-hidden>{Array.from(g.name)[0]?.toUpperCase()}</div><div className="guest-row-name"><h3>{g.name}</h3><small>Kapasitas {g.max_people} orang · {g.active?'Tautan aktif':'Tautan nonaktif'}</small></div><span className={'guest-status guest-status-'+(g.response?.attendance||'waiting')}>{g.response?ATTENDANCE[g.response.attendance]:'Belum menjawab'}</span></div>
    {g.response&&<div className="guest-response"><p><strong>{g.response.people} orang</strong> direncanakan hadir · {new Date(g.response.updated_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p>{g.response.message&&<><blockquote>{g.response.message}</blockquote><small>{g.response.consent?`Nama publik: ${g.response.display_name} · ${g.response.moderation==='approved'?'Disetujui':g.response.moderation==='pending'?'Menunggu moderasi':'Disembunyikan'}`:'Ucapan privat. Tamu tidak memberikan izin tampil.'}</small>{g.response.consent&&<div className="button-row guest-moderation"><button className="button small" disabled={locked||g.response.moderation==='approved'} onClick={()=>act('moderate',g.id,g.response!.revision,{moderation:'approved'})}>Setujui ucapan</button><button className="button ghost small" disabled={locked||g.response.moderation==='hidden'} onClick={()=>act('moderate',g.id,g.response!.revision,{moderation:'hidden'})}>Sembunyikan</button></div>}</>}</div>}
    {edit===g.id&&<form className="guest-inline-edit" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('update',g.id,g.revision,{name:String(f.get('name')||''),max_people:Number(f.get('capacity'))});}}><label>Nama<input name="name" defaultValue={g.name} required maxLength={100}/></label><label>Kapasitas<input name="capacity" type="number" min={1} max={10} required defaultValue={g.max_people}/></label><button className="button small" disabled={locked}>Simpan</button><button type="button" className="button ghost small" onClick={()=>setEdit(null)}>Batal</button></form>}
    <div className="button-row guest-actions"><button className="button small" disabled={!appEnabled||!book.live||!g.active||!!linkBusy||locked} onClick={()=>reveal(g)}>{linkBusy===g.id?'Memuat…':'Tautan & WhatsApp'}</button><button className="button ghost small" disabled={locked} onClick={()=>setEdit(edit===g.id?null:g.id)}>Edit</button><button className="button ghost small" disabled={locked||(!g.active&&!book.can_manage)} onClick={()=>{if(confirm(g.active?'Nonaktifkan tautan ini? Jawaban disimpan, tetapi dikeluarkan dari rekap aktif dan ucapan publik.':'Aktifkan kembali tautan? Ucapan yang disetujui dapat tampil kembali.'))void act('activate',g.id,g.revision,{active:!g.active});}}>{g.active?'Nonaktifkan':'Aktifkan'}</button><button className="button ghost small" disabled={locked} onClick={()=>{if(confirm('Ganti kunci tautan? Tautan lama tidak dapat digunakan lagi. Anda perlu membagikan tautan baru. Jawaban sebelumnya tetap disimpan.'))void act('rotate',g.id,g.revision,{});}}>Ganti kunci tautan</button></div>
   </article>)}</div>
   <div className="guest-pagination"><span>{book.total?`${book.offset+1}–${Math.min(book.offset+PAGE_SIZE,book.total)} dari ${book.total}`:'0 hasil'}</span><div className="button-row"><button className="button ghost small" disabled={loading||book.offset===0} onClick={()=>load(Math.max(0,book.offset-PAGE_SIZE))}>← Sebelumnya</button><button className="button ghost small" disabled={loading||book.offset+PAGE_SIZE>=book.total} onClick={()=>load(book.offset+PAGE_SIZE)}>Berikutnya →</button></div></div>
  </section><aside className="guest-sidebar"><GuestAdd key={addEpoch} disabled={locked||!book.can_manage||book.stats.registered>=MAX_GUESTS} add={guests=>act('add_many',null,0,{guests})}/><GuestSettings key={book.settings.revision} settings={book.settings} disabled={locked} canManage={book.can_manage} save={data=>act('settings',null,book.settings.revision,data)}/><div className="panel guest-help"><span className="eyebrow">TETAP TERKENDALI</span><h3>Tamu melihat seperlunya.</h3><p>Daftar, kapasitas, dan konfirmasi tidak dipajang ke publik. Ucapan baru atau yang diedit harus mendapat persetujuan lagi.</p><p>Undangan umum tetap dapat dibaca lewat alamatnya. Tautan personal hanya membatasi siapa yang bisa mengisi RSVP.</p><Link className="text-link" href="/panduan#tamu-rsvp">Baca panduan tamu →</Link></div></aside></div>
 </main>;
}
function GuestAdd({disabled,add}:{disabled:boolean;add:(guests:{id:string;name:string;max_people:number}[])=>Promise<void>}){
 const [names,setNames]=useState(''),[capacity,setCapacity]=useState(1),[error,setError]=useState('');
 return <section className="panel"><span className="eyebrow">UNDANG ORANG TERDEKAT</span><h2>Tambah tamu</h2><form onSubmit={e=>{e.preventDefault();setError('');const list=names.split(/\r?\n/).map(n=>n.trim()).filter(Boolean);if(!list.length||list.length>MAX_BATCH){setError('Isi 1–25 nama, satu nama/rombongan per baris.');return;}void add(list.map(name=>({id:crypto.randomUUID(),name,max_people:capacity})));}}><fieldset disabled={disabled}><label>Nama tamu / rombongan<textarea value={names} onChange={e=>setNames(e.target.value)} rows={6} maxLength={2600} required placeholder={'Bapak Budi & keluarga\nIbu Sari\nRina dan pasangan'}/></label><label>Maksimal orang per nama<input type="number" min={1} max={10} required value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><p className="field-help">Satu baris = satu tautan. Maksimal 25 nama per penambahan. Periksa daftar setelah menyimpan agar nama tidak ditambahkan dua kali.</p><button className="button full" type="submit">+ Simpan daftar tamu</button></fieldset>{error&&<p role="alert" className="notice error">{error}</p>}</form></section>;
}
function GuestSettings({settings,disabled,canManage,save}:{settings:GuestWorkspace['settings'];disabled:boolean;canManage:boolean;save:(data:{accepting:boolean;show_wishes:boolean})=>Promise<void>}){
 const [accepting,setAccepting]=useState(settings.accepting),[show,setShow]=useState(settings.show_wishes);
 return <section className="panel"><span className="eyebrow">KENDALI PEMILIK</span><h2>Penerimaan</h2><form onSubmit={e=>{e.preventDefault();void save({accepting,show_wishes:show});}}><fieldset disabled={disabled}><label className="guest-checkbox"><input type="checkbox" checked={accepting} disabled={!canManage&&!accepting} onChange={e=>setAccepting(e.target.checked)}/><span><strong>Terima RSVP</strong><small>Izinkan tamu mengirim dan memperbarui jawaban.</small></span></label><label className="guest-checkbox"><input type="checkbox" checked={show} disabled={!canManage&&!show} onChange={e=>setShow(e.target.checked)}/><span><strong>Tampilkan ucapan</strong><small>Hanya ucapan berizin yang sudah Anda setujui.</small></span></label><button className="button ghost full" type="submit">Simpan pengaturan</button></fieldset></form><p className="field-help">Menutup RSVP tidak menghapus jawaban. Menonaktifkan ucapan menghentikan penayangan baru; salinan/screenshot yang sudah dibuat tamu tidak dapat ditarik kembali.</p></section>;
}
