import DeleteDraftButton from '@/components/DeleteDraftButton';
import Link from 'next/link';
import { requireUser } from '@/lib/server-auth';
import type { Invitation,Order } from '@/lib/types';
import { getTemplate } from '@/lib/templates';
import LogoutButton from '@/components/LogoutButton';
import { STATUS_LABEL,currency } from '@/lib/domain';
export const dynamic='force-dynamic';
export const metadata={title:'Dashboard',robots:{index:false,follow:false}};
export default async function Dashboard({searchParams}:{searchParams:Promise<{notice?:string}>}){
 const {db,user}=await requireUser(); const query=await searchParams;
 const [{data,error},{data:admin},{data:orders,error:orderError}]=await Promise.all([db.from('ki_invitations').select('*').eq('owner_id',user.id).order('updated_at',{ascending:false}).limit(20),db.rpc('ki_is_admin'),db.from('ki_orders').select('*').eq('owner_id',user.id).order('created_at',{ascending:false}).limit(20)]);
 const invitations=(data||[]) as Invitation[];
 return <main className="container workspace"><div className="workspace-heading"><div><span className="eyebrow">RUANG CERITA ANDA</span><h1>Undangan saya.</h1><p>{user.email}</p></div><div className="button-row">{admin===true&&<Link className="button ghost small" href="/admin">Admin</Link>}<Link className="button ghost small" href="/dashboard/pesanan">Pesanan saya</Link><Link className="button ghost small" href="/dashboard/tamu">Tamu & RSVP</Link><Link className="button ghost small" href="/dashboard/akun">Akun saya</Link><Link className="button" href="/dashboard/baru">+ Buat draft</Link><LogoutButton/></div></div>{query.notice==='admin-only'&&<p className="notice error">Halaman admin hanya untuk akun yang diberi akses oleh pengelola.</p>}<div className="notice">Draft di sini tetap privat. Untuk menerbitkan, buka Pesan & terbitkan, selesaikan verifikasi pembayaran, lalu terbitkan versi yang sudah diperiksa.</div>
 {error?<div className="notice error">Draft tidak berhasil dimuat. Periksa migrasi SQL dan aturan akses Supabase. Ini bukan berarti data Anda kosong.</div>:!invitations.length?<div className="empty-state"><span aria-hidden>✦</span><h2>Cerita Anda dimulai di sini.</h2><p>Pilih desain favorit dan simpan draft pertama Anda.</p><Link className="button" href="/tema">Jelajahi tema ↗</Link></div>:<div className="dashboard-grid">{invitations.map(inv=><article className="panel draft-card" key={inv.id}><span className="badge">DRAFT PRIVAT</span><h2>{[inv.content.groom,inv.content.bride].filter(Boolean).join(' & ')||'Undangan baru'}</h2><p>{getTemplate(inv.theme_slug)?.name||inv.theme_slug} · {inv.content.eventDate||'Tanggal belum diisi'}</p><small>Versi {inv.revision} · {new Date(inv.updated_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</small><div className="button-row"><Link className="button small" href={`/dashboard/undangan/${inv.id}`}>Edit draft</Link><Link className="button ghost small" href={`/dashboard/undangan/${inv.id}/preview`} target="_blank" rel="noopener noreferrer">Preview ↗</Link></div><div className="button-row"><Link className="button ghost small" href={`/dashboard/undangan/${inv.id}/pesan`}>Pesan & terbitkan →</Link></div><DeleteDraftButton id={inv.id} revision={inv.revision}/></article>)}</div>}
 <section className="section compact"><h2>Permintaan pengerjaan</h2><p>Permintaan bukan konfirmasi lunas atau penerbitan.</p>{orderError?<p className="notice error">Riwayat permintaan belum dapat dimuat.</p>:!(orders||[]).length?<p className="muted">Belum ada permintaan.</p>:<div className="dashboard-grid">{(orders as Order[]).map(order=><article className="panel" key={order.id}><span className="badge">{STATUS_LABEL[order.status]}</span><h3>{order.order_code}</h3><p>{getTemplate(order.theme_slug)?.name||order.theme_slug}</p><strong>{currency(order.total_price)}</strong><small>Harga referensi saat permintaan dibuat, bukan bukti pembayaran.</small></article>)}</div>}</section></main>;
}
