import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {requireUser} from '@/lib/server-auth';
import {UUID,currency,parseDraft} from '@/lib/domain';
import {readyToPublish,type CommerceSettings} from '@/lib/commerce';
import {checkoutAppEnabled} from '@/lib/commerce-server';
import CheckoutForm from '@/components/commerce/CheckoutForm';
export const dynamic='force-dynamic';
export const metadata={title:'Pesan undangan',robots:{index:false,follow:false}};
export default async function Checkout({params}:{params:Promise<{id:string}>}){const{id}=await params;if(!UUID.test(id))notFound();const{db,user}=await requireUser('/dashboard/undangan/'+id+'/pesan');const{data:version,error:ve}=await db.rpc('ki_schema_version');if(ve||version!==7)return <main className="container workspace"><h1>Aktifkan skema tahap 6.</h1><p className="notice">Jalankan migrasi 006 setelah 001–005, kemudian periksa koneksi di /setup.</p><Link href="/setup" className="button">Buka pemeriksaan</Link></main>;
 const [{data:d,error:de},{data:sale,error:se},{data:cfg,error:ce}]=await Promise.all([db.from('ki_invitations').select('*').eq('id',id).eq('owner_id',user.id).maybeSingle(),db.from('ki_sales').select('id').eq('invitation_id',id).eq('owner_id',user.id).maybeSingle(),db.from('ki_commerce_settings').select('*').eq('id',1).single()]);if(de||se||ce)throw new Error('CHECKOUT_LOAD_FAILED');if(!d)notFound();if(sale)redirect('/dashboard/pesanan/'+sale.id);const {data:t,error:te}=await db.from('ki_templates').select('slug,name,price').eq('slug',d.theme_slug).eq('active',true).eq('category','pernikahan').maybeSingle();if(te)throw new Error('QUOTE_LOAD_FAILED');if(!t)return <main className="container workspace"><h1>Tema belum tersedia.</h1><Link href={'/dashboard/undangan/'+id}>Kembali ke editor</Link></main>;
 const errors=readyToPublish(parseDraft(d.content,user.id)),settings=cfg as CommerceSettings;
 return <main className="container workspace"><Link className="back-link" href={'/dashboard/undangan/'+id}>← Kembali ke editor</Link><div className="workspace-heading"><div><span className="eyebrow">DARI DRAFT KE UNDANGAN</span><h1>Pesanan Anda.</h1><p>Periksa rincian sebelum membuat tagihan.</p></div><span className="badge">BELUM DIBAYAR</span></div><div className="commerce-grid"><div>{errors.length?<div className="panel"><h2>Lengkapi draft dahulu.</h2>{errors.map(x=><p className="notice" key={x}>{x}</p>)}<Link className="button" href={'/dashboard/undangan/'+id}>Lengkapi editor</Link></div>:<CheckoutForm owner={user.id} id={id} revision={d.revision} theme={t.slug} name="" price={t.price} settings={settings} enabled={checkoutAppEnabled()&&settings.checkout_enabled}/>}</div><aside className="panel commerce-summary"><span className="eyebrow">RINGKASAN PAKET TEMA</span><h2>{t.name}</h2><p>{d.content.groom} & {d.content.bride}</p><strong className="commerce-price">{currency(t.price)}</strong><dl className="commerce-facts"><div><dt>Undangan</dt><dd>1 undangan per pesanan</dd></div><div><dt>Masa aktif</dt><dd>{settings.active_days} hari sejak verifikasi pembayaran</dd></div><div><dt>Acara & galeri</dt><dd>Maksimal 3 acara · 6 foto</dd></div><div><dt>Pembayaran</dt><dd>Transfer bank · verifikasi admin</dd></div><div><dt>Tema publik</dt><dd>Sesuai tema pada pesanan</dd></div></dl><p className="notice">Harga ini dibaca dari database. RSVP mengikuti aktivasi pengelola. Musik instrumental dan rekening hadiah tersedia melalui editor. QR check-in, custom domain, dan pembayaran otomatis belum tersedia.</p><small>Tidak perlu mentransfer sebelum nomor pesanan dan rincian rekening muncul.</small></aside></div></main>;
}
